### ISSUE TITLE
Publishing the application packages to a running site fails with file in use error

### ISSUE THREAD

**Issue by vijayrkn** [aspnet/dnx#1068]
Scenario impacted:
Publishing an application ( with no source option) from VS.

When the application packages are published to a running site in Azure, publish fails with file in use error. 

Similar issue - Consider shadow copying when loading DLLs #219

**Comment by Eilon** [comment]
Also related: https://github.com/aspnet/Hosting/issues/141

**Comment by rubenprins** [comment]
Any update on this issue?

Because, isn't the scenario much broader here: if you're publishing **any** .dll (from a project reference, nuget package, no source publish) without completely stopping the hosting process (such as IIS).

If that's true, that's pretty much a show stopper when you're hosting from Azure or IIS (and solved by ASP.NET vCurrent over a decade ago in v1.0).

Having to stop the hosting process on every server in a web farm (if you even have access to them!) is a huge problem.

ASP.NET should never ever be allowed to lock files, period.
