### ISSUE TITLE
Console runtime needs to search for any class.Main() as entry point

### ISSUE THREAD

**Issue by xqiu** [aspnet/dnx#122]
When converting a console program to projectK, it took me a while to realize that I need to change the 
    public class OldClassName
to
  public class Program
in order for the k run to find the proper entry point of the console program.

Otherwise, error returned as:
'CreateZip' does not contain a static 'Main' method suitable for an entry point

I think we should fix it to make it compatible with normal console project.

**Comment by jskeet** [comment]
Could we at least make the error message more specific?

> 'ProjectName' does not contain a Program class with a Main method suitable as an entry point

(And is there any restriction on namespace here?)

**Comment by davidfowl** [comment]
I thought it was specific enough? https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Framework.Runtime.Common/Impl/EntryPointExecutor.cs

**Comment by jskeet** [comment]
No, because it requires the type to be called Program, with no indication of that within the error message.

To put it another way: I was banging my head against this error for a while before I found this bug entry, at which point it was really easy to fix. If the error message had specified that it was looking for a type called Program, I'd have fixed it immediately.

(It looks like this requires it to either be in the global namespace or with a namespace the same as the assembly name, too - am I right? If so, again, that would be worth stating in the error message.)

**Comment by Eilon** [comment]
Reopening, this message is quite lame.

**Comment by jcansdale** [comment]
This confused me as well. Even when my 'Main' method is static, the containing class must have a public constructor and a new object is created (when not required).

**Comment by MiKom** [comment]
This a clear departure from old style C# applications where class with `Main()` function could be named in any way and have private default constructor. IMHO, this information is both not properly conveyed to the user at runtume and not emphasized enough in the doc: http://docs.asp.net/en/latest/dnx/console.html

People will be scratching their heads about it.

**Comment by Eilon** [comment]
@MiKom thanks, we're looking at some improvements to make `Program.Main()` feel more familiar to existing .NET devs.

**Comment by davidfowl** [comment]
Irrelevant with the new CLI work
