### ISSUE TITLE
`kpm packages add ...symbols.nupkg` appears to succeed but ignores the package content

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnx#1409]
should either provide an option to include .pdb files in the regular NuPkg archives or allow symbol packages to add files to existing packages folders.

example failure:
1. `build --quiet install` in the MVC repo
2. `cd artifacts/build`
3. `ls *symbols*|% { kpm packages add $_.Name }`
4. observe for example
```
Adding NuGet package Microsoft.AspNet.Mvc.6.0.0-t150315000957.symbols.nupkg to C:\Users\dougbu\.dnx\packages
Installing Microsoft.AspNet.Mvc 6.0.0-t150315000957
Add complete, 24ms elapsed
...
```

5. (should be step 5) `ls -r $env:userprofile\.dnx\packages\*.pdb`
6. observe very few such files; none from step 4
7. similarly the symbol packages and NuSpec files do not exist in their target packages folders.

**Comment by davidfowl** [comment]
There's no support for this yet but I agree that this should be a "thing". For now skip symbol packages because it'll just mess things up.

**Comment by dougbu** [comment]
fyi I've been using the following workaround, updating the target version each time
```
pushd .\artifacts\build
dir -dir -name|% {
  cp $_/dnx451/$_.pdb $env:userprofile/.dnx/packages/$_/6.0.0-t150318041706/lib/dnx451/ }
dir -dir -name|% {
  cp $_/dnxcore50/$_.pdb $env:userprofile/.dnx/packages/$_/6.0.0-t150318041706/lib/dnxcore50/ }
popd
```

**Comment by ChengTian** [comment]
This was fixed by the PR fixing https://github.com/aspnet/dnx/issues/1726
`dnu packages add` now checks SHA of the package and overwrites installed package if SHAs don't match. `<PackageName>.symbols.nupkg` has different SHA as `<PackageName>.nupkg`, so we have the desired behavior now:
![capture](https://cloud.githubusercontent.com/assets/1383883/8389837/f30b4896-1c2e-11e5-9a65-3406a692e83a.PNG)
