### ISSUE TITLE
kpm bundle writes empty entries in web.config

### ISSUE THREAD

**Issue by MattGal** [aspnet/dnx#1434]
I've been experimenting with publishing latest ASP.NET 5 applications to places I can publish them to... IIS, Windows Azure, and most recently WIndows Azure Pack.

Due to some funkiess with the publish profile for Windows Azure Pack (entirely could be my fault), I ended up trying to publish via FTP to my hosted site.  Seems reasonable.  To do this I expected I could just run KPM bundle, and if it succeeded I'd simply copy over the approot/wwwroot directories to the server.

Unfortunately, when I did this, despite there being an active and default  selected DNX version, web.config ends up looking like this:

```
 <  appSettings  >
    < add key="kpm-package-path" value="..\approot\packages" />
    < add key="bootstrapper-version" value="1.0.0-beta4-11278" />
    < add key="runtime-path" value="..\approot\packages" />
    < add key="dnx-version" value="" />
    < add key="dnx-clr" value="" />
    < add key="dnx-app-base" value="..\approot\src\WebApplication1" />
  < / appSettings >
```

... lacking a dnx-version and dnx-clr seems to break functionality.  When I look at the same file after publish to Azure, I consistently see a version and "clr"  (or CoreCLR, probably) when I browse to the SCM for the site.

I see this as two bugs: 
1) Bundle isn't doing what it's supposed to
2) Bundle isn't failing despite what seems to be a failure mode.

**Comment by ChengTian** [comment]
It is actually an expected behavior.

When you do `kpm bundle` without `--runtime` option, you mean you are going to deploy the bundled output to somewhere that already has DNX installed. In this case, we leave `dnx-clr` and `dnx-version` blank and bootstrapper will look for the DNX installed in your environment.

If you are deploying to an environment that doesn't have DNX installed, for example Windows Azure Website, you need to do something like
```
kpm bundle --runtime dnx-clr-win-x86.1.0.0-beta3
```

It makes sure the DNX runtime is also bundled to your output and can be used when you deploy/run your app.

**Comment by davidfowl** [comment]
@MattGal We're revisiting this https://github.com/aspnet/dnx/issues/1530
