### ISSUE TITLE
Give project.json data to the hosting/application layer

### ISSUE THREAD

**Issue by Praburaj** [aspnet/dnx#1475]
Currently hosting and secretmanager has to read `wwwroot` and `usersecretsId` values from `project.json`. So they end up reading the `project.json` again at their own layers. It will be nice to give the project.json data to the layers above so that they can avoid reading the project.json again. 

@glennc @davidfowl

**Comment by anurse** [comment]
I'd rather avoid giving arbitrary project.json data from the runtime to the application. It means the runtime has to provide some kind of interface to this arbitrary data, which means we end up with gross things like `IDictionary<string, object>` where the type of "object" is mostly arbitrary, or grosser things like `IProjectConfigurationPropertyElementProvider`

Here's my personal preference, @davidfowl can comment on his thoughts.

1. The Runtime parses what it understands out of `project.json` and provides it through _structured_ POCOs/Interfaces.
2. We provide a "Project Parsing" library that participates in Dependency Resolution like normal, and apps can take a dependency on that. This will reparse the project, but **can cache it** and allow more arbitrary access to the project since we can version it easier. For sake of argument call it `Microsoft.ProjectModel` (literally not even my proposed name, just a name for now)

As a result, if you want well-known project stuff, you don't reparse the project. If you want to read things like "secretId" or other arbitrary things, you parse the project a second time and it can be cached inside this parser component.

If @davidfowl is still concerned about the perf of this scenario, I can accept something more flexible in the runtime interface. I want to keep the runtime->application interface as tight as possible since it versions in a different (and less flexible) way. Adding a large surface area like extracting arbitrary project properties is kinda scary for that.

I would be OK with exposing the entire project.json text to the application so it doesn't have to re-load it from disk...
