### ISSUE TITLE
dnu restore/build/pack should allow globbing patterns

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#1495]
dun build/restore/pack should should support globbing patterns so make recursive restore/build easier and more efficient. 

```
dnu build src/** - Build all projects under the src folder recursively.
dnu restore samples/* - Restore all projects directly under samples
```
By default, these commands should only work on the current project or allow passing in a target project.

**Comment by davidfowl** [comment]
Build supports globbing but restore doesn't /cc @ChengTian

**Comment by ChengTian** [comment]
Here is the "globbing" currently used by `dnu restore`:
For `dnu restore <path>`,
1. If `<path>` is a `project.json`, only restore for it
2. If `<path>` is a directory which contains a `project.json`, only restore for the `project.json`
3. If `<path>` is a directory which doesn't contain any `project.json`, recursively find all `project.json` and restore for all of them.

I assume we want to remove the logic above because they can be expressed with globbing patterns. Also, having two rules combined can be confusing.

**Comment by muratg** [comment]
@davidfowl Are there any usage patterns you'd like that's not supported with the Wei's explanation above?  To me, it seems to cover all the important cases.  

It's not the same syntax as build but I feel that's fine.

**Comment by 0xdeafcafe** [comment]
did this go anywhere? Having it behave in the same manor `dnu restore` would he fantastic.

**Comment by khellang** [comment]
With all the globbing support being added here and there, is it worth pulling this functionality into its own little library, i.e. `System.IO.FileSystem.Globbing` under [corefxlab](https://github.com/dotnet/corefxlab/)? Or has this already been done somewhere?

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#592
