### ISSUE TITLE
kpm bundle does not delete the src folder under approot when we pass 'no-source' option' to an existing folder 

### ISSUE THREAD

**Issue by vijayrkn** [aspnet/dnx#1502]
If i run kpm bundle to an existing folder with source files, kpm bundle does not delete the src folder.

Repro:
kpm.cmd bundle "C:\WebApplication2" --out "C:\Temp\AspNetPublish\WebApplication2-89" --configuration Release --no-source --runtime dnx-clr-win-x86.1.0.0-beta4-11296 --wwwroot-out "wwwroot" --quiet

Issue:
Runtime always builds from source if the src folder is present. 

'No-source' option and configuration option becomes meaningless in this case.

**Comment by davidfowl** [comment]
Simple fix to this would be to remove the sources/projects entry from global.json

**Comment by davidfowl** [comment]
/cc @muratg This is tricky. Today we don't delete before publishing, so the question is do we want to treat this like a special case. If you publish source and then `--no-source` to the same folder, it won't work because the project loader always wins over the package loader. Now I think it's a bug that VS doesn't use a fresh folder everytime but maybe there's a good reason for that?

@vijayrkn @mayurid What's the reason for reusing the same folder?

**Comment by vijayrkn** [comment]
We have made the change in VS to delete the temp folder every time before publish. This should take care of this issue.
