### ISSUE TITLE
Add AssemblyFileVersion attribute to all assemblies

### ISSUE THREAD

**Issue by joeloff** [aspnet/dnx#1504]
Assemblies do not currently contain an AssemblyFileVersion attribute. This attribute is used by Windows Installer to determine whether or not a file can be upgraded.

We should add something like  DNX_ASSEMBLY_FILE_VERSION

Any installer that consumes these will be broken when doing upgrades from one build to the next as files could be skipped.

**Comment by pranavkm** [comment]
There's also the `AssemblyInformationalVersion` which might need something similar.

**Comment by davidfowl** [comment]
We already infer that from the version in project.json

**Comment by pranavkm** [comment]
Doesn't help if I want to use build time information to set it (for instance it would be nice to set the commit shas in the binaries we produce)

**Comment by victorhurdugaci** [comment]
Here is a proposal that's not for the two PRs that I sent because they go in the release branch. It is for the dev branch.

I don't think that the Roslyn compiler should have this logic embedded in it.The file version and the commit hash should be compiler preprocess steps added by the app. But, instead of adding the preprocess step to each project, we could either add it to `global.json` (does that work today?) or have an environment variable that specifies extra folders to look for compiler process files. So, KoreBuild would included these preprocess steps and apps consume them.

What do you think?
