### ISSUE TITLE
Improving NullReferenceException: Reporting what was null?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/dnx#1620]
@davidfowl Following a comment made by [Joel Kauffman](https://www.linkedin.com/pub/joel-kauffman/10/390/100) @ifranto on [.NET Rocks!](http://dotnetrocks.com/default.aspx?showNum=1122) today, is it possible for NullReferenceException to report more detail on the source of the exception? I think everyone has had a few "object reference not set to instance of object" head scratchers. Can it throw with more detail (e.g., if we pass a null var to something not expecting it, can it state the var as part of the exception)?

**Comment by Eilon** [comment]
This sounds like more of a scenario for either [Roslyn](https://github.com/dotnet/roslyn) or [Core CLR](https://github.com/dotnet/coreclr). Not much we would do in the DNX.

BTW I experimented with something like this a while ago by plugging in a Roslyn syntax tree rewriter. I'd scan for all places where exceptions are explicitly thrown (i.e. `throw <something>`) and rewrite it to inject extra data into the exception that wouldn't otherwise be there (e.g. the method parameter values, etc.).

**Comment by GuardRex** [comment]
Yes, I posted in the wrong place. I'll move this.
