### ISSUE TITLE
Don't use console color with CoreCLR on Linux/Darwin

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#1708]
Because CoreCLR temporarily doesn't support console color on those platforms.

We should bring tests back on those platforms when this issue is done: https://github.com/aspnet/dnx/commit/7b297209f2031a0343a346719345e7db1eac0bfd

**Comment by ellismg** [comment]
There's no way to get the current foreground or background color of the terminal in *Nix.  We are hesitant to try to lie because given the default settings for different terminals, there's no good initial value we can use.

Changing the color and resetting both work, it's just getting the current color that throws PlatformNotSupported exception.  I do not expect this will change.
