### ISSUE TITLE
F# support

### ISSUE THREAD

**Issue by ErikSchierboom** [aspnet/dnx#1714]
I'd love to see F# support, similar to how [VB support will be added](https://github.com/aspnet/dnx/issues/1706).

**Comment by KodrAus** [comment]
+1 for F# support

**Comment by spencerwi** [comment]
Another +1, as F# is the whole reason that I'd try to do .NET work (as a Linux/OSX dev)

**Comment by itajaja** [comment]
yay! +1

**Comment by muratg** [comment]
Language support (including VB.NET) is not in scope for V1. Putting this one to Backlog as well.

**Comment by jskulavik** [comment]
@davidfowl [pointed out how this could be achieved long ago](https://github.com/aspnet/dnx/issues/1706), @Alxandr already gave it a go, and we've now got beta 7+ to work with possibly using [this](https://github.com/davidfowl/vNextLanguageSupport) as a spring board.  Given that ASPNET5 is an OSS project, why shouldn't the 'community,' in this case the outstanding F# community, contribute?  The new MSFT is *give **and** take* folks, no longer just give, and we shouldn't just take, but give.  I'm personally +100 for the support of F#, but let's make it happen as a community rather than demand this already overloaded team just provide it like they did in the MSFT of old.

**Comment by spencerwi** [comment]
@jskulavik As you pointed out, @Alxandr did already give it a go. This issue is, as I understand it, about *official* support for F# (a Microsoft language) on Microsoft's own .NET language runtime, using *stabilized* APIs, rather than *unofficial* support against *beta* APIs.

Trust me, I've tried quite a bit using and digging into Alxandr's YoloDev work, but the problem right now is that aspnet/vNext are in such a "move fast and break everything" phase right now that community support is far from stable.

**Comment by jskulavik** [comment]
@spencerwi Great point!  My only real point was that the community could help out and ideally shorten the development time associated making the *official* support come to life.  Pull requests are a beautiful thing, and I'm sure the ASPNET5 team would love to exercise the out-of-band development approach.

**Comment by muratg** [comment]
Thanks folks, as @jskulavik pointed out, the team is overloaded with V1 so had to cut some features to make room for core features + stability. These were hard cuts to make, and we're planning to bring most of these back post V1. (That's why these issues are not closed.)  

That being said, I personally love F# and hope to see some community supported F# support in the meantime.

**Comment by Alxandr** [comment]
I'd just like to point out that the API used to implement the F# compiler on top of DNX has been mostly stable for months. I've had to make a few, really small changes, due to refactorings in DNX, but nothing that has taken any major effort or rewrite. I'm not saying go use my YoloDev F# support in production or anything (I mean, the name should give you that hint if anything), but all in all it's just a plug for the actual F# compiler to compile your code (as opposed to Roslyn), so the output should in general be just the same as if you used the actual F# compiler. Also, if you wanted to take it to production, you'd most like produce binaries locally, (or on CI) before doing so, in which case it wouldn't much matter either way, because the YoloDev compiler plug wouldn't even be loaded.

Also, @spencerwi, if there's anything you don't understand about the current compiler plug implementation, I'll be happy to answer any questions :) (I just might not notice them being asked, so just scream at me a little if you don't get a reply within a day or two :P ).

**Comment by KodrAus** [comment]
I'm wondering what 'F# support in DNX' should look like idealy. Is a plug to the F# compiler sufficient, or should support for F# go down to Roslyn?

**Comment by davidfowl** [comment]
Roslyn supporting F# really has nothing to do with the DNX. The compiler API in DNX is separate from roslyn itself. It just happens to be our default experience.

**Comment by KodrAus** [comment]
@davidfowl I get that, I'm trying to be philosophical
