### ISSUE TITLE
[Regression] Latest dnx changes causes 'dnu publish' to fail

### ISSUE THREAD

**Issue by suhasj** [aspnet/dnx#1796]
EDIT- version number

With build 11706 of dnx, the command `dnu publish` fails when passing the `--runtime` flag. This was caused by recent changes in lock file and publish code.

**Comment by GuardRex** [comment]
FYI: This didn't repro in my `dnu publish` with `dnx-coreclr-win-x64.1.0.0-beta5-11706` and with `--runtime active --no-source`. My publish was :+1:

**Comment by suhasj** [comment]
My bad the dnx version I faced the issue is `11706`

**Comment by GuardRex** [comment]
I can't repro your issue with `dnu publish` for `dnx-coreclr-win-x64.1.0.0-beta5-11706` with `--runtime active` and `--no-source`. My publish was :+1:

**Comment by suhasj** [comment]
Hmm interesting. I tried clr x86. Can you confirm with that ?

**Comment by GuardRex** [comment]
It failed; however, these apps I'm working with are `coreclr` only. I changed the framework to `dnx451` and did receive exceptions for ...
```
Type or namespace name 'Http' does not exist in System.Net.
Type or namespace name 'HttpClient' could not be found.
Type or namespace name 'HttpRequestException' could not be found.
```
... but I think that's just because my dependencies are messed up for `dnx451`. I do see a strange mention of ...
```
System.InvalidOperationExecption: The given root is invalid at 
Microsoft.Framework.PackageManager.RestoreCommand.
<ExecuteCommand>d__68.MoveNext()
```
When I go back to `dnxcore50` and `dnx-coreclr-win-x64.1.0.0-beta5-11706`, the `dnu publish --runtime active --no-source` goes fine ... compiles with no warnings, no errors, and no mention of an invalid root.

**Comment by muratg** [comment]
:watch:
