### ISSUE TITLE
Sending a FilesChanged doesn't always stop the IIS Express process

### ISSUE THREAD

**Issue by BillHiebert** [aspnet/dnx#1843]
1. Create a new DNX Site
2. Ctrl+F5 to run it
3. Note the IIS Express process id
4. Open project.json and save it.
5. Most of the time the IIS Express process is not restarted

I can repro it with .cs files as well.

**Comment by muratg** [comment]
@Tratcher any ideas?

**Comment by Tratcher** [comment]
Modifying startup works. I noticed that the PID only changes if I have accessed/refreshed the page since the last change. I think this is because sites are delay started, they only initialize (and listen for file changes) if someone actually visits the site.

Modifying the project.json does not appear to trigger a process close, and it's harder to tell if you've actually changed anything in the site.

**Comment by davidfowl** [comment]
Likely a DTH bug. I made a change here in beta5 that might have something to do with it.

**Comment by muratg** [comment]
Assigning to @davidfowl to investigate the potential DTH issue, but to me there doesn't seem to be a functional impact. I think we can just close it.

**Comment by davidfowl** [comment]
Closing this as by design.
