### ISSUE TITLE
Add a CLI flag to have dnu perform a restore but suppress the execution of any scripts defined in project.json

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/dnx#1874]
Add a CLI argument to have dnu perform a restore but suppress the execution of any scripts defined in project.json.
e,g,
```
dnu restore --no-scripts
```

This will need to be used by the VS project system to suppress execution of scripts when doing restores in VS.

**Comment by muratg** [comment]
@ChengTian We'll need to do this in soon, so that WTE can start using it and testing with it.

**Comment by ChengTian** [comment]
We can finish this quickly because @davidfowl already added an internal flag for it. I can just expose this to external users:
https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Framework.PackageManager/Publish/PublishProject.cs#L416

I'll follow the @davidfowl 's option name and make it `dnu restore --skip-restore-events`

**Comment by muratg** [comment]
:+1:
