### ISSUE TITLE
If the feed has a 301 redirect, it doesn't work as a package source

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#1907]
When you run one of the `dnu` commands and specify a fallbacksource using `https://myget.org` instead of `https://www.myget.org`, it will not work. `https://myget.org` responds with a 301 and redirects to `https://www.myget.org`

**Comment by ChengTian** [comment]
Turns out `https://myget.org` is redirecting us to `http://www.myget.org`. Note that, in addition to the `www` prefix, the redirection also changes `https` to `http`.

Try it in your browser with `https://myget.org/F/aspnetvolatile/api/v2/FindPackagesById()?id='Microsoft.AspNet.Authentication.OpenIdConnect'`

Our HttpClient doesn't allow this kind of downgrading (@Tratcher , good job :+1: )

@maartenba @xavierdecoster , I guess this is a bug introduced recently in myget.org?

**Comment by maartenba** [comment]
We've been doing redirects indeed. After seeing this issue, we updated the naked domain (without www) to go directly to our cloud services. Can you give it another go and see if this fixes the behaviour you were seeing?

**Comment by anurse** [comment]
FYI, a redirect is fine, it just needs to be https -> https. Right now it's https -> http.

**Comment by maartenba** [comment]
Can you give it another go and see if it's good now?

**Comment by ChengTian** [comment]
Yeah, it is good now.
