### ISSUE TITLE
Setting a specific DNX runtime when creating new projects

### ISSUE THREAD

**Issue by leosbrf** [aspnet/dnx#1946]
When creating a new project in Visual Studio 2015 RC (Version 14.0.22823.1 D14REL and .NET Framework 4.6.00057)
1-ASP .NET Web Application (.NET Framework 4.6)
2-Select a template (Website)

Error:

---------------------------
Microsoft Visual Studio

---------------------------
The project system has encountered an error.

Cannot find the DNX runtime 'dnx-clr-win-x86.1.0.0-beta5-11781'. Please install the runtime using 'dnvm install' command, then close and reopen the solution. For more details about getting the runtime, see https://github.com/aspnet/home.

A diagnostic log has been written to the following location: "C:\Users\leonardo\AppData\Local\Temp\VsProjectFault_7a1c1081-e827-4498-8314-092264e01e72.failure.txt".

-----------------
I wish to create it using 1.0.0-beta4. How can I set this? I ran "dnvm use 1.0.0-beta4", but it seems VS 2015 did not care.

**Comment by glen-84** [comment]
You can set the SDK version in your `global.json` file.

**Comment by leosbrf** [comment]
Thanks for the answer. So, everytime I create a project I have to do this? That is not a problem, though. But I've created a project called ASPNETvnext (empty) that does not have a global.json. I would like to know where I can config this property in this specific case, because when I open it the error above is thrown.

**Comment by glen-84** [comment]
> So, everytime I create a project I have to do this?

Currently, when you use a VS project template, it will use the default SDK. This is an issue since the default SDK might not be compatible with the dependencies referenced in the project template. For this reason, it is most-likely going to change so that a specific template is "pinned" to a specific version of the SDK. So, a template created for beta4 will use the beta4 SDK by default.

> But I've created a project called ASPNETvnext (empty) that does not have a global.json.

An empty ASP.NET 5 web application does have a global.json file (it's under solution items). Which project template did you use?

**Comment by davidfowl** [comment]
The case where VS doesn't make the global.json is when you add an ASP.NET 5 application or project to an existing solution. 

Can you move this bug to the aspnet/Tooling repository.

**Comment by leosbrf** [comment]
Ok, I've opened a new issue here:
https://github.com/aspnet/Tooling/issues/84
