### ISSUE TITLE
Package restore doesn't work for myget feed

### ISSUE THREAD

**Issue by awec** [aspnet/dnx#2022]
Noticed something odd today when trying to add a new myget feed for some CI packages and then trying to restore them in VS Express for Web (beta4). Not sure if it's a bug but logging just in case. 

I added the new feed: https://myget.org/F/nancyfx/ and that was fine. In my project.json, I added a reference to Nancy at version 1.3-Pre1524 (the latest build available on myget).

When trying to package restore it downloaded the nupkg into the NuGet cache (AppData/Local/nuget/cache).

However, when trying to actually restore, it always failed with the error:

Installing NuGet package Nancy.1.3.0-Pre1524.
Successfully installed 'Nancy.1.3.0-Pre1524' to RFL.
========== Finished ==========
Restoring packages for C:\Users\awec\Source\Personal\RFL\project.json
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='Nancy'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='Nancy'
  CACHE https://myget.org/F/nancyfx/FindPackagesById()?Id='Nancy'
Unable to locate Nancy >= 1.3.0-Pre1524
Writing lock file C:\Users\awec\Source\Personal\RFL\project.lock.json
Restore complete, 844ms elapsed
Errors in C:\Users\awec\Source\Personal\RFL\project.json
    Unable to locate Nancy >= 1.3.0-Pre1524

Both packages were in the cache folder, e.g.: C:\Users\awec\AppData\Local\NuGet\Cache\Nancy.1.3-Pre1524.nupkg

If I manually copy the nupkg and extract it to the packages folder (C:\Users\awec\.dnx\packages\Nancy\1.3-Pre1524\Nancy.1.3-Pre1524.nupkg) then VS detects it fine and it works:

Restoring packages for C:\Users\andcoll\Source\Personal\RFL\project.json
Writing lock file C:\Users\andcoll\Source\Personal\RFL\project.lock.json
Restore complete, 990ms elapsed

No issues at all in vs2013 (i.e. vCurrent)

**Comment by awec** [comment]
After discussing this with @davidfowl it seems this is caused by the lack of the www. in the myget feed URL that I added. 

Not sure exactly why that is a problem though, nor how it manages to work in vs2013 with the same URL (no www).

**Comment by pranavkm** [comment]
Perhaps `dnu restore` doesn't follow redirects?

**Comment by davidfowl** [comment]
@pranavkm it does but the question is when is the redirect applied. It happens too late when dnu restore sees it because myget doesn't preserve the entire query string args when redirecting to https. NuGet.exe seems to apply the redirect to the base feed address. We might need to do something similar.

**Comment by maartenba** [comment]
The www-less URL on MyGet is just a convenience and should not be used for feeds. That said, MyGet rewrite rule has been modified to also add full query string.

Please mention @maartenba or @xavierdecoster on anything related to MyGet.

**Comment by muratg** [comment]
Seems like the redirect issue. https://github.com/aspnet/dnx/issues/1907

**Comment by ChengTian** [comment]
Seems not a redirect issue.

@awec , your dnu restore output shows that all your HTTP requests hit our local HTTP cache and there was no HTTP request sent.

We cache the response of an HTTP request for at least 30min. So please delete your %userprofile%/AppData/Local/dnu/cache if you want to upload a package to a feed and let this new package be visible to `dnu restore` immediately.

`myget.org` and `www.myget.org` have different cache keys and that's why adding `www` fix the problem.

**Comment by maartenba** [comment]
We've been doing redirects indeed. After seeing this issue, we updated the naked domain (without www) to go directly to our cloud services. Can you give it another go and see if this fixes the behaviour you were seeing?

**Comment by maartenba** [comment]
Think this one can be closed?

**Comment by anurse** [comment]
It looks like you are correct.

If anyone still has this issue, feel free to continue commenting or re-open this issue.
