### ISSUE TITLE
Set configuration file for .NET Framework to App.config next to the appbase

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#2194]
This will improve the compatibility with ConfigurationManager for .NET 4.x libraries running on DNX 45x

**Comment by muratg** [comment]
Putting this into beta 7 for now

**Comment by jods4** [comment]
App.config or web.config? Both would work of course, but given that people running under IIS will probably have a web.config inside wwwroot anyway, it may make sense to reuse it.

**Comment by davidfowl** [comment]
It would be web.config for IIS

**Comment by anurse** [comment]
I'm going to need more context on this before I can do anything. @davidfowl does this App.config file need to be different for each framework (probably...)? Do we need to put anything in it or just have it there and point the SetupInformation at it so that configuration works?

**Comment by jods4** [comment]
I can speak for my use-case, which was what prompted @davidfowl to create this issue (but he didn't include the context).

I run ASP.NET 5 on top of IIS and .NET 4.6 (Core is not a target). In this context I use some libraries that rely on things found in `web.config` and can't be configured otherwise.

Example right from Microsoft: EF6 + Oracle. It _needs_ the Oracle provider to be configured in the `DbProviderFactories`. No luck though, because in .NET 4.6 there is _no_ way to configure the `DbProviderFactories` outside of `System.Configuration.ConfigurationManager` (i.e. `web.config`). 

Now the drama is that `System.Configuration` uses `APP_CONFIG_FILE` from `AppDomain` data to find its config file. But it is set wrong by ASP.NET 5 running on its own web server and when I get a chance to set it it's too late.

For me, this issue is about making sure that when ASP.NET 5 runs on .NET 4.6, `System.Configuration` works properly to maintain compatibility with non-Core libraries (i.e. picking up `web.config` or `app.config` at the right place if they exist). It's clear that in Core, this doesn't matter and Core libraries should use the new Configuration APIs.

**Comment by anurse** [comment]
Ah, that helps. Thanks!

**Comment by anurse** [comment]
@jods4 To be clear, are you using IIS or one of self-hosting webservers like WebListener? As far as I can tell, IIS is setting the web.config location correctly (to `wwwroot/web.config`)

**Comment by jods4** [comment]
@anurse I would need to redo some tests to be sure of that. We started with `dnx . web` but then when VS 2015 RTM came we switched to that (and hence IIS Express -- this reflects our deployment environment better).

If I trust my old self I wrote this: 
> But it is set wrong by ASP.NET 5 running on its own web server 

So that would be consistent with your findings.

I will perform a quick test tomorrow and let you know.

**Comment by anurse** [comment]
I'm also going to test it out on IIS, but if you do still encounter the issue in IIS specifically, re-open this bug and let me know :)

**Comment by anurse** [comment]
(and for your reference, the fix is in DNX 1.0.0-beta7-12359 and higher, so if you don't see that on the feed yet, it's because our build is delayed :P)

**Comment by anurse** [comment]
I've verified it seems to be working in IIS. Note that IIS uses the `wwwroot/web.config` file, not the `app.config` file because it is hooked in with the whole IIS pipeline :)

**Comment by jods4** [comment]
@anurse I removed my dirty hack and tested my app in IIS: it seems to work on beta-6 indeed. So I think my report above was accurate: this is only a problem with WebListener.

Using `wwwroot/web.config` is exactly what I would have expected in that context. That makes perfect sense I think.

**Comment by anurse** [comment]
:+1: Note that after this fix, WebListener will use `[project root]/app.config` and **not** `[project root]/wwwroot/web.config`. This is because `web.config` is an IIS concept, and when using WebListener your app is behaving more like a Console App than an IIS app. It also allows your app to have IIS-specific configuration.

If this seems surprising to you, we can discuss it further.

**Comment by jods4** [comment]
@anurse Oh, _now_ I see why you made that comment. It seemed obvious but now it's not!

It is a bit surprising / inconsistent I guess. Ideally, the same app should be able to run on IIS and WebListener interchangeably.

`web.config` is indeed an IIS concept -- especially `<system.webServer>` -- but not _just_ that. I started with ASP.NET 1.1 and at that time we learned to configure ASP.NET with `<connectionStrings>`, `<appSettings>` and friends; and I don't even think `<system.webServer>` existed (those were the IIS 5 / 6 days).

To me and probably a lot of other people, I think of `web.config` (also) as the .NET configuration file for ASP.NET websites. While -- of course -- `app.config` is the .NET configuration file for standalone applications.

If it doesn't have far reaching implications, I would consider poking for `wwwroot/web.config` first and then fallback to `app.config`. I think that would make sense for a lot of people and enable hosting the same project on both IIS _and_ WebListener. I did not think this through, though.

**Comment by anurse** [comment]
My concern is that WebListener and Kestrel are just console apps that happen to listen on HTTP ports. At the time we're loading the configuration file, we have no idea what kind of app is in use and to have the app.config ignored just because there happened to be a `wwwroot/web.config` file seems surprising. Connection Strings and App Settings are handled completely differently in ASP.NET 5 (via `IConfiguration`), so `web.config` and `app.config` are only intended for use with legacy .NET code (in fact they **do not** work on CoreCLR because it does not support that configuration system). I think the minor inconvenience of having to duplicate some .NET framework settings in order to work in both WebListener and IIS is better than the potential user confusion caused by accidentally reading the wrong config file.

This is mostly a point-in-time problem. As more things transition to the newer system, this pain will be dramatically reduced. There is definitely value in embracing legacy support, but I think here it isn't clear how best to do it, so the safer option is to give the user the most control.

**Comment by davidfowl** [comment]
This is no different to how things work today.

**Comment by jods4** [comment]
First, let me say that I don't feel strongly about this issue as at this point we are only running on IIS and being able to `dnx web` is a bonus but I don't really care if it doesn't work.

Don't be too quick to dismiss "legacy .NET". I know a lot of enterprises are going to run ASP.NET 5 on top of the full .NET framework (4.5+). If only just because lots of 3rd party libraries that are important are not compatible with .NET Core (we do). Maybe I am wrong but I don't get the impression that the message communicated by MS is that full framework has become "legacy".

Assuming that running on full .NET is still a mainstream scenario (is it?), there are lots of libs out there that are not .NET Core aware and may not be before long (if ever...). And in fact this is a key motivation to run on full .NET. Some of those may be dependent of "old" `System.Configuration`. Ideally libs would accept other way to get their configuration (via APIs, etc.) so that we could feed them from `IConfiguration`, but it's not always possible. Case in point: MS' own core framework. What I want to say here is that making `System.Configuration` work on full .NET is certainly more than a "legacy", nice-to-have, thing.

From the same line of thought: "As more things transition to the newer system [...]". Maybe you should clarify MS thinking regarding the full framework, but I don't think everything is going to be ASP.NET 5 / Core -ready soon. Don't get me wrong, I get the benefits of Core even when running on Windows only. But yet I believe .NET Core will mostly interest the cross-platform developpers, _at least_ at first.

Now back to the issue. Who is affected? 
- Only people who use `web.config` --> Full framework target / Windows only.
- Only people who want to run on both IIS and `dnx web` --> certainly few, except...
- ... People who develop on VS Code and deploy on IIS.

Is that a lot of people? I have no idea.
Is it acceptable that they have to essentially duplicate their config so that it works in both environment? It's very annoying (risk of forgetting to copy the config when making changes); but at least _it 
works_ and could be automated during the build/publish.

As I said I don't care too much about `dnx web`, this is just my feedback about this issue.
