### ISSUE TITLE
Lightweight publish option for end-user deployment

### ISSUE THREAD

**Issue by xanather** [aspnet/dnx#2195]
I think there should be an option when publishing to use a minimalistic approach that is focused towards only including the files which are needed to run a project.

Something like a singular folder with all code included:
/Project.dll
/dnx.exe
/dnx.dll
/mscorlib.dll
/CoreCLR.dll
/Start.cmd
/etc...

Right now publish just copies the whole runtime directory and --no-source creates a hierarchy of folders which are not really needed if DNX is running a single .dll and all needed managed libraries is included in the base directory (this is what I currently do manually).

This would help deploying desktop (and server) apps. The generated/copied files would be targeted towards a specific platform only (based on which DNX/DNU is being used to publish).

Could also include a option to pre-JIT the project too since the output is just targeting one platform.

If this is out of scope for DNX and is is not the right place for this that's fine, maybe the CoreCLR corefxlab repos? Just let me know. DNX seems like it will be the "official" bootstrapper for CoreCLR, I think something like this should eventually be added.

**Comment by davidfowl** [comment]
Besides size of the deployment, what's the motivation? What's wrong with the project.json and folder hierarchy staying around? Why does it need to be flat?

**Comment by xanather** [comment]
Well, besides size being the main reason, it would just be easier to manage and simplifies deployment.

It will make it easier and straightforward to update existing/installed DNX apps with other/side-by-side DNX apps that have been published in this manner.
I also hit Windows NT MAX_CHAR limit far too easy with DNX's hierarchy publish which results in DNX immediately crashing and closing itself.

Are there any benefits the hierarchy serves, is it to be able to include multiple runtimes? - aren't the nuget packages platform-specific anyway? What was the decision behind it?

The project.json which contains configuration/entry point information could also exist in the flat folder.

I mean if there are good reasons why the publish hierarchy exists then just having an option to trim output files/only include what is needed from the publish command sounds just as good.

I have been copying the actual .dll's of NuGet packages, the DNX runtime, and the compiled DNX .dll into one singular folder and invoking DNX with the name of the project .dll and its been working fine, for me I see no benefit having all those folders on deployment.

**Comment by muratg** [comment]
Please feel free to continue the discussion. Moving to 1.0.0 backlog milestone until we make a decision.

**Comment by masonwheeler** [comment]
`Besides size of the deployment, what's the motivation?`

*Deployment.*

It really is that simple.  Looking at the world through ASP-colored glasses, that may not look like it makes much sense,  but when this is used as part of the CoreCLR machinery, it needs to be made friendly for deployment to desktop and mobile systems.

Project.json and all the folder hierarchy of dependencies should be considered *source;* the finished product should be as simple (and small) as possible!

**Comment by davidfowl** [comment]
As small as possible has nothing to do with folder hierarchy. We have the folder hierarchy for several reasons:

- We support servicing of packages and the dnx itself. So if there's a security issue, we can patch a machine and have the dnx pick that up for particular packages. We reuse the folder hierarchy so that we don't have to have a different code base for groking flat assemblies. The CoreCLR doesn't have any servicing support.

- `dnu publish` is web specific, if anything this would be an option on `dnu build`.

- Today the layering of the dnx makes is such that NuGet assembly resolution and other services (dynamic compilation go away) when you use the lower layer. This is our default experience and even though we do support `dnx.exe foo.dll` it's not a mainline experience for us. 

- Side by side runtimes works so you can deploy a portable application that runs on multiple platforms. We do this for some of our dnx based console applications (it's a very npm install -g experience).

- Consistency between development and publishing. The published image is just a smaller version of what you get during development (global packages folder etc). 

- The DNX provides a bunch of services that the application can use. Today the services are different depending on what layer you run at. This can be tweaked but that's how it works today and the lower layer has very little to offer (which might be fine in some cases).

The DNX is really a nuget aware runtime, that tries to avoid copying anything anywhere at all costs. It loads thing in place and can treat a folder full of source files as an assembly. 

Now to answer specific comments:

> Well, besides size being the main reason, it would just be easier to manage and simplifies deployment.

Size is important all around. We actually want to support publishing a minimal set of files for web deployment as well. As or ease of management, I think people are just used to a flat list of files. It would be easier to have a single file :smile:. This also assumes single architecture/os etc. This really isn't what the DNX is about. Something like corerun is better suited for this.

> This would help deploying desktop (and server) apps. The generated/copied files would be targeted towards a specific platform only (based on which DNX/DNU is being used to publish).

See the above answer. We haven't designed anything for desktop applications although people have built some windows forms things on top of the dnx and it works great!

> I also hit Windows NT MAX_CHAR limit far too easy with DNX's hierarchy publish which results in DNX immediately crashing and closing itself.

That's unfortunate :smile: 

> It really is that simple. Looking at the world through ASP-colored glasses, that may not look like it makes much sense, but when this is used as part of the CoreCLR machinery, it needs to be made friendly for deployment to desktop and mobile systems.

What mobile systems are people using the DNX for?

> Project.json and all the folder hierarchy of dependencies should be considered source; the finished product should be as simple (and small) as possible!

Except it's not, it's actually used at runtime. 

> If this is out of scope for DNX and is is not the right place for this that's fine, maybe the CoreCLR corefxlab repos? Just let me know. DNX seems like it will be the "official" bootstrapper for CoreCLR, I think something like this should eventually be added.

For v1 it certainly is. The main scenario for v1 is ASP.NET and global console applications. BTW what you're asking is more a dnu option. The CoreFX team still use msbuild + dnu to produce flat folders that are architecture and os specific. That might be something to look at. I think corerun is probably the lowest level you can work at as there are no restrictions or structure imposed on your application. It's a folder full of dlls + and exe, that sounds more like what you want.

**Comment by xanather** [comment]
Thanks for the detailed reply,

Given that for the foreseeable future DNX is targeting web mostly I think your right about me to just try use CoreRun.

Regarding using CoreRun, I just have problems integrating it with Visual Studio (such as enabling debugging with CoreRun etc) while the DNX integration inside VS is really good, which is why I picked DNX as the bootstrapper. I think VS templates are needed to be developed for it. Is there somewhere I could voice this? I know DNX, CoreCLR and CoreFX all aren't really the places for such a request. Anyway I will look into trying to use CoreRun again.

I will still leave this issue open as I think DNX should still support more lightweight publishings (or builds) in the future.

**Comment by davidfowl** [comment]
With the new dotnet CLI this should be possible.

**Comment by MartinJohns** [comment]
@davidfowl Please don't close tickets because something **should** be possible. Close it when it either **is** possible, or it was decided that this is not supported.

**Comment by xanather** [comment]
@MartinJohns Your right, his wording is slightly off, but yes this is possible in CLI (which is due to replace DNX in the next RC release I think).
