### ISSUE TITLE
Consume namespace/scheme of nuget spec correctly

### ISSUE THREAD

**Issue by troydai** [aspnet/dnx#2210]
We essentially ignore the xml namespace while searching element (check `ElementsNoNamespace` extension method). It is because there are customer packages missing schema.

**Comment by davidfowl** [comment]
@troydai What's the purpose of this bug?

**Comment by troydai** [comment]
/cc @moozzyk 

The current manifest reader doesn't care about xml namespace when searching for element. It works but it's not an ideal behavior. Completely ignore namespace could introduce ambiguous when duplicate elements present in the same manifest.

**Comment by davidfowl** [comment]
So you mean that all of the nuget packages will still work but we want to refactor our code to be more xml friendly?

**Comment by troydai** [comment]
Yes.
1. If an NuGet specific xml namespace present, using that namespace to search element in this subtree;
2. Fallback to namespace ignore when there isn't namespace;

**Comment by moozzyk** [comment]
After the conversation we had with @pranavkm I don't think we need to do anything here. What we have is quite ugly but the source of the problem is that NuGet does not really use Xml correctly. I would just leave it as is because nuspecs are not intended to be extended and hence what we have will not cause problems. What @troydai proposes is probably the most elegant solution in current situation but I don't think it has any other significant advantage over what we have now.
