### ISSUE TITLE
`dnx . test` and other "implicit build" commands hide compilation warnings

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnx#2284]

**Comment by dougbu** [comment]
For example,
1. Change a test class to include something like
``` c#
        private class PrivateClass
        {
            public string name;
        }
```
(MVC repo has an example of this as we speak: `MutableObjectModelBinderTest` in test/Microsoft.AspNet.Mvc.Core.Test includes `PersonWithNoProperties` which looks like the above sample.)
2. `dnu build --quiet`
3. observe following (expected) warning in the output
```
C:\dd\dnx\MVC\test\Microsoft.AspNet.Mvc.Core.Test\ModelBinding\MutableObjectModelBinderTest.cs(1807,27): warning CS0649: Field 'MutableObjectModelBinderTest.PersonWithNoProperties.name' is never assigned to, and will always have its default value null
```
4. `dnx . test`

Expected: To see same warning in addition to the test run information.
Observed: Only the test run information is displayed:
```
xUnit.net ASP.NET test runner (32-bit DNX 4.5.1)
Copyright (C) 2015 Outercurve Foundation.

Discovering: Microsoft.AspNet.Mvc.Core.Test
Discovered:  Microsoft.AspNet.Mvc.Core.Test
Starting:    Microsoft.AspNet.Mvc.Core.Test
Finished:    Microsoft.AspNet.Mvc.Core.Test

=== TEST EXECUTION SUMMARY ===
   Microsoft.AspNet.Mvc.Core.Test  Total: 1910, Errors: 0, Failed: 0, Skipped: 0, Time: 3.095s
```

**Comment by davidfowl** [comment]
There's no good way to show warnings at runtime.

**Comment by anurse** [comment]
Plus, warnings are for compilation/development-time only, not runtime. That's what `dnu build` is for.

**Comment by anurse** [comment]
At best, this sounds like a feature that xunit could add. The runtime could help out, but it's an application level feature here.

**Comment by dougbu** [comment]
Our build system only executes test projects, never runs `dnu build` on them. But warnings in test projects show up in VS. For example the warning described in my first comment would be visible in the Error List. This is an annoying inconsistency I was hoping we could correct within `dnx . test`.

But :ok: perhaps its better to think of this as a `Universe` (`KoreBuild`) gap... Of course we'd have to balance warning discovery against built performance.

Thoughts?

**Comment by anurse** [comment]
In the DNX repo I believe we `dnu build` tests, but that is extra, somewhat wasted, work. I could maybe buy a Runtime feature that allows an application to retrieve any diagnostics related to a dependency (compilation errors/warnings, etc.) so it can render it. That could possibly be a way for xunit to get this data.

In short, it sounds like a useful feature for `dnx . test` specifically, but we need to be careful because I don't think it's useful in general runtime scenarios. I also think that changing `KoreBuild` to `dnu build` tests first could be a useful first pass and if that's sufficient for now, we can defer this work outside the overcrowed `1.0.0` milestones :)

**Comment by dougbu** [comment]
Filed aspnet/Universe#248. Given that work, probably fine to put this issue on the backlog.

**Comment by anurse** [comment]
The proposal in this enhancement is basically to consider exposing compilation issues in a way that xunit can retrieve.
