### ISSUE TITLE
Implement Analyzers

### ISSUE THREAD

**Issue by muratg** [aspnet/dnx#2311]
~~Min bar is dev dependencies~~

Design below

**Comment by anurse** [comment]
Dev dependencies are a much more complicated feature and aren't necessary to do this. We can do it with regular dependencies just fine.

**Comment by anurse** [comment]
@davidfowl @troydai and I talked and Fowler wants Troy to take a look at this. /cc @muratg

**Comment by muratg** [comment]
@anurse yes, thanks. It was to be assigned to @troydai, but I was waiting before we get a priority on Friday's design meeting.

**Comment by anurse** [comment]
Fair enough, @troydai was just wondering why he hadn't been assigned :).

**Comment by troydai** [comment]
__Recognize analyzer assemblies in library__
* Add property to `LibraryExport` for analyzers
* Update `ProjectExportProviderHelper.GetExportsRecursive` to compile analyzers from the lock file.
* Feed analyzers list to `RoslynCompiler`

__Drive the analyzing process__
* Extract `DiagnsoticAnalyzer` from the analyzers references
* Update `RoslynCompiler` to create compilation with analyzer and get diagnostics

__Output__
* Mix error and warning in build result
* Ensure DTH works well in VS

**Comment by anurse** [comment]
Note: make sure that the analyzer assemblies are loaded in a separate `IAssemblyLoadContext`

**Comment by troydai** [comment]
Open questions:
1. Do we want to run all the analyzers in a closure to all the projects?
2. A switch to the analyzing?

**Comment by davidfowl** [comment]
Consider the impact on design time as well. He language service needs the list of analyzer assemblies

**Comment by glennc** [comment]
@davidfowl should either come to design meetings or stay on vacation.... ;)

**Comment by giggio** [comment]
You also need to somehow allow users to enable and disable specific diagnostic ids. On .csprojs this is done through the Rules Editor window, I suggest this goes into project.json, on something like `compilationOptions`. Integration with the Rules Editor window (or a window that looks like it) is nice to have but not at all a "must have" IMO. Also, are you going to consider .ruleset files at all? Again, I don't think those are necessary, these could all go into project.json. But it would be nice to have a way to share those settings between projects.

**Comment by giggio** [comment]
This was expected for beta7, and is now back to the backlog. Should we expect this on beta8? If I understand correctly, features that don't make to beta8 won't make to RTM, as beta8 is supposed to be feature complete, right? So the question follows: is this expected to be present on RTM?

**Comment by davidfowl** [comment]
@giggio Nope, it's been cut. See the roadmap https://github.com/aspnet/Home/wiki/Roadmap

**Comment by giggio** [comment]
:( :( :(

**Comment by iaingalloway** [comment]
Just to make sure I'm understanding correctly:- This means we won't be able to use Roslyn analyzers in asp.net 5 RTM projects?

**Comment by davidfowl** [comment]
@iaingalloway That's correct. Ones from nuget packages. The VSIX based ones will likely just work (tho that needs to be confirmed)

**Comment by dmccaffery** [comment]
This makes me very, very sad.

-.-

::sniffles::

**Comment by thomas-darling** [comment]
@davidfowl I understand you're busy trying to get the RTM done, but this is really a quite critical feature, and one we expected would be in RTM. In the roadmap you linked to, there's no mentioning of this feature being cut.

We're about to begin a major rewrite of a very large codebase, and not having support for StyleCop analyzers makes it quite hard for us to enforce our coding conventions. And not only that, but some of the default analyzers do appear to be running, and they are actively working AGAINST our coding guidelines, even though they are based on your own StyleCop rules.

Case in point:
One of the default analyzers suggests removing "this." when it is not strictly nessesary, but we happen to strongly disagree with that suggestion - an opinion supported by StyleCop rule SA1101:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1101PrefixLocalCallsWithThis.cs
Because we cannot disable this analyzer, Visual Studio now actively encurages our developers to break our coding guidelines, and even going as far as to suggest "fixing" this in the entire solution, and thus turning our entire codebase into a mess.

Support for analyzers, and especially for configuring the default ones, should really be among your top priorities, and something you should work very hard to get into the RTM release.

**Comment by dmccaffery** [comment]
I am in agreement; developers are OCD about these types of things.

As a side note to @thomas-darling: I was able to work around the IDE001-003 analyzer issues through some R# magic. It still darkens the this keyword, but it no longer squiggles it or light bulbs it. Same for the fully-qualified namespaces in using statements.

**Comment by giggio** [comment]
You can still use analyzers through extensions. It is only the nuget usage that is not implemented. It is not ideal, but it works.

**Comment by davidfowl** [comment]
Moving ASP.NET to the new dotnet CLI this will be implemented over there.

https://github.com/dotnet/cli/issues/83
