### ISSUE TITLE
Project references: Allow referencing with a name different than the containing folder

### ISSUE THREAD

**Issue by muratg** [aspnet/dnx#2312]

**Comment by anurse** [comment]
Thoughts (just a bit of a brain dump to facilitate discussion/design):
* We could allow a `path` property under the dependency. That starts to smell a lot like `HintPath` though...
* We could allow a project.json to have an **optional** `name` property to change the name of the project. This would mean someone has to scan all the project.json files in scope in order to determine the name of each project. Perhaps we could do that during `dnu restore` and put it in the lock file?

**Comment by troydai** [comment]
If the scope of the problem is limited to "Allow a different project reference name to be used other than folder name". The solutions are simple:

__Solution 1.1__
	
_Move the folder name to a "localName" property and assign the new name as the key of the reference._

```JSON
{
    "dependencies": {
        "NewAlpha": { "version": "1.0.0", "localName": "Alpha" }
    }
}
```

__Solution 1.2__
	
_Load in dependency project's project.json and use "id" or other property to determine the actual name. Downside of this solution is that project.json of dependencies need to be actively_

__However when we expand the boundry of the problem to include solving the duplicate project references name among the search paths issue, there are more aspects and solution to consider.__
 
_Repo: https://github.com/troydai/dnx-2312/tree/master/samples/Zero_

Error:
```
System.InvalidOperationException: The project name 'Alpha' is ambiguous between the following projects:
/Users/troydai/code/playground/dnx2312/samples/GroupA/Alpha
/Users/troydai/code/playground/dnx2312/samples/GroupB/Alpha
```

__Solution 2.1__
_Automatic adding suffix to the project name when duplicate names are found._

```
For example
	GroupA/Alpha => Alpha.1
	GroupB/Alpha => Alpha.2
```
Pro: 
  a. Project.json schema keeps intact;
  b. ProjectInformation is still evaluated lazily
  c. Automatic
Con:
  a. Confusing project names;
  b. Make it hard to track error base on output;
  c. Can't guarantee the name's persistence
	
__Solution 2.2__
_Read in "name", "id" or other properties from dependency's project.json to determine a name._
Pro:
  a. Intuitive;
  b. Achievable without changing project.json schema
Con:
  a. Performance: project.json need to be actively load (Mitigation: optimized the JsonDeserializer to load partial data.);
  b. If the properties are missing from dependency's project.json, need to fall back solution.

__Solution 2.3__
_Add a "hint" path in project.json_
```		
{
    "dependencies": {
        "Alpha.A": { "version": "1.0.0", "hintPath": "../../GroupA/Alpha" },
	"Alpha.B": { "version": "1.0.0", "hintPath": "../../GroupB/Alpha" }
    }
}
```
Con
  a. Real hint or deterministic path?
  b. Relative vs absoulte
  c. I thought you all hate MSBuild

**Comment by muratg** [comment]
I like the second option, although I'm sure @davidfowl will have some (probably reasonable) perf concerns.

**Comment by troydai** [comment]
Proposal 1: Lock file based project reference map

The motivation behind this change is to allow referencing different projects under folders with same name. With that been said, when referenced projects are indeed identical or different version/iteration of same projects the ambiguous should still be treated as an exception.

Key pillars:

__Project Name__
Refine the concept of project name. Add a property `id` to the project.json schema. The value of the property is used as project name when it presents. The folder name as project name is a fallback strategy.

__Project references map in lock file__
One of the downside of using project.json property to determine project name is the performance hit. 

For runtime, this can be mitigated by introduce a projects reference map in the lock file, which maps from project name to the relative path to the referenced projects' project.json files. 

Scenarios:

__dnu restore__

When `ProjectResolver` is initialized it loads all project.json in the search paths, deserialize them and resolve the actual name. To optimize the performance, the deserialized json objects should be cached.

At this stay with the assistance of property name, if there are still ambiguous names exception will be thrown and procedure will be terminated.

The referenced project names and relative paths will be eventually written in the lock file.

__dnx run / dnu build__

Other than relies on `ProjectResolver` to resolve projects, lock file is load and projects map is used to local the referenced projects.

Issues:

* Further complicate the lock file;
* Changing project name requires a dnu restore;
* Introduce paths in the lock file

Option:

* Avoid touch the lock file. Load name from project.json every time. Using a performance optimized deserializer to read just enough content to determine the name.

**Comment by anurse** [comment]
> Introduce paths in the lock file

This is my biggest concern but I don't see a better way if we want to support this.

Looks like a reasonable first pass at design to me. We'll discuss in the meeting :+1:

**Comment by troydai** [comment]
I'm not absolutely sure about the `path` in locks file, either.

**Comment by davidfowl** [comment]
See https://github.com/aspnet/dnx/issues/1559

**Comment by davidfowl** [comment]
Lock file is the way to go here.

**Comment by anurse** [comment]
Yeah, it's pretty much the only option, which is what we landed on. It's unfortunate that it makes the lock file no longer portable, but I think that was inevitable (and wasn't really something you could rely on anyway).

**Comment by Eilon** [comment]
Moving to Backlog - we are not planning on doing this feature for v1. The workaround for now is to rename the folder to have the desired name.

@troydai can you close out the PR for now? We will revisit in the future.

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#569
