### ISSUE TITLE
Fix help text of 'dnu sources'

### ISSUE THREAD

**Issue by kichalla** [aspnet/dnx#2325]
![image](https://cloud.githubusercontent.com/assets/6559784/8857591/6a553bde-3127-11e5-8392-635f50f4f8ec.png)

'related managing' -> 'related to managing'
'packages source code' -> 'source code of packages' OR 'packages' source code'?

**Comment by Eilon** [comment]
How about: `Commands for managing source code of packages.`

**Comment by kichalla** [comment]
Sounds good to me.

**Comment by dougbu** [comment]
This problem is more general than that one-liner. Help for `dnu sources` has a number of issues:
1. Output of `dnu sources --help` mentions "Use "sources [command] --help" for more information about a command." but does not list any (sub-)commands. Where should the user go from here?
2. `dnu sources get --help` (should you be so lucky as to discover that sub-command) doesn't work. Instead it throws a `System.Exception: TODO: Error: unrecognized argument '--help'` and shows a useless stack trace. This conflicts with the general help mentioned in 1.
3. `dnu sources` actually (checking source) only supports the single sub-command (`get`). So why all the mystery? `dnu sources get` should simply _be_ `dnu sources`. (Maybe not. `dnu sources` really should do what `dnu feeds` does. Changing NuGet terminology while in the midst of a grand unification is counter-productive. I'd expect a command such as `dnu fetch-sources` to do what the current `dnu sources get` does.)

Separately `dnu feeds` (again, better-named as `dnu sources`) has all of the above issues as well. At least there, it's easier to imagine further sub-commands (beyond `list`) eventually coming e.g. `dnu feeds disable ...` or (hopefully) `dnu sources disable ...`.

**Comment by Eilon** [comment]
@dougbu Re 1. it does list a command `get`:

```
C:\Users\elipton>dnu sources


Usage: dnu sources [options] [command]

Options:
  -?|-h|--help  Show help information

Commands:
  get  Retrieves the source code for packages used by projects

Use "sources [command] --help" for more information about a command.
```

Getting help for that command does indeed crash, and that's obviously a bug, which you mention in 2. Please log a new bug for this (unless there's a dup).

I disagree with 3. because even if there's only one sub-command now, we need to think about adding future commands.

As far as the naming of `feeds` vs. `sources` that's a good point - please log a separate bug for that.

**Comment by dougbu** [comment]
:ok: new issues
- for 2.: #2347
- for naming side issue: #2448
