### ISSUE TITLE
"build" dependencies should affect other projects through p2p dependencies 

### ISSUE THREAD

**Issue by lodejard** [aspnet/dnx#2361]
For example, in a solution if project `A` depends on project `B`, and project `B` has a "build" dependency on package `C` and a "build" dependency on project `D`, then from the point-of-view of `A` the `B` project does not depend on `C` or `D`.

This makes p2p "build" on `B` works the same way as if it was a nupkg reference to package `B`.

**Comment by davidfowl** [comment]
Sounds good. Makes build for p2p deps sound like private dependencies

**Comment by davidfowl** [comment]
We need to figure out if this is a build time trick or if we make `dnu restore` aware of build time dependencies listed in `project.json`

**Comment by roji** [comment]
If I'm understanding things correctly, build dependencies could create problems in addition to the transitive dependency issue described above.

Say my project A has a build-type dependency on project B. B may support only some frameworks (e.g. dnx451), but my project A needs to support additional frameworks (e.g. dnxcore50). This shouldn't be a problem in principle, but unless I'm mistaken I won't be able to build A for dnxcore50 because its dependency B doesn't support it.

Hope this makes sense.
