### ISSUE TITLE
dnu.exe should support init to create a minimum project.json file

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/dnx#2375]
To have parity with other projects, we should support an init call (dnu or other tool) to create a minimum project.json like "bower init", "npm init", and other tools do. Yeoman is great, but when you want full control, this would be a nice set of parity with other web toolkits.

**Comment by anurse** [comment]
I like this. It doesn't have to be a full template, just a base project.json.

**Comment by glennc** [comment]
We've talked about this a whole lot, but never actually implemented it. I wouldn't be against it, but I don't know that it fits into the roadmap for 1.0 as it stands right now. If someone wanted to grab this and work through the design of it with us we would probably accept it though :).

**Comment by mholo65** [comment]
What should be supported? How should it work?

1. Should it be interactive, should it accept params? Or both? (-i / --interactive)
2. Should it also support generation of global.json file? (-g / --global)
3. Should it support modifying an existing project.json/global.json? I.e. try to load if exist in dir?
4. What should be modified? Version, Authors, Description?
5. Default frameworks? dnxcore50 on Win/Linux/Mac and dnx451 on Win?
6. Other stuff? Commands, Dependencies, Webroot, Exclude, etc...

A minimal simple project.json could be as following:
```json
{
  "version": "0.1-alpha",
  "authors": ["John Doe"],
  "description": "A wonderful library that does nice stuff",
  
  "code": ["**/*.cs"],
  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  }
}
```

**Comment by davidfowl** [comment]
This shouldn't be a dnu command but instead should be a standalone global command.

**Comment by anurse** [comment]
I disagree for simple project.json scenarios. Complex templating and scaffolding should be separate but almost all other package managers/build tools have been successful with a simple initialization system (`npm init`, Maven Archetypes, `cargo new`, etc.). Initializing a simple new project shouldn't require a completely separate set of tools.

I like `cargo`'s approach to this (http://doc.crates.io/index.html). The `init` command would have three modes:

* `dnu init` - Console App targeting both `dnx451` and `dnxcore50`. Just a simple `run` command
* `dnu init --lib` - Class library targeting `dotnet`
* (maybe) `dnu init --web` - Like Console App but with empty Startup.cs instead of Program.cs. It would need a `web` command, so it would probably need to have Hosting as a dependency, so I'm not convinced this is worth it.

This isn't about generating something for all scenarios, it's about generating a simple, empty, project manifest. Having to either get a new global command or read detailed docs just to figure out how to create a project.json is a barrier that we can remove.

**Comment by davidfowl** [comment]
This should totally be outside of dnu. Scaffolding can get complex really quickly (just look at our yeomen templates) and we shouldn't couple this to dnu (which is already doing too much).

**Comment by anurse** [comment]
Which is why this is essential that it is not scaffolding. It's why I'm not really sure a "Web Project" initializer is useful. In the other two cases (Console and Class Library) I envision it only creating a very simple project structure with absolutely no dependencies.

Right now, creating a DNX project from outside Visual Studio requires a lot of extra tools and I don't like that. We should be building a simple self-contained story for the basic case. More complex templating absolutely belongs in external tools, but the actual layout of a project manifest is already coupled to DNU so a simple DNU command that knows how to produce something like the below is not scary at all to me

```json
{
    "dependencies": {
    },
    "frameworks": {
        "dotnet": {}
    }
}
```

**Comment by davidfowl** [comment]
I'm against this being in dnu itself.

**Comment by anurse** [comment]
Well if you're going to get all tautological about it :stuck_out_tongue: ...

If we have the ability to produce (`pack`, `wrap`, `build`, etc.) and consume (`restore`) packages in dnu then I don't see a problem with a simple command to initialize a project (which is how we expect people to create packages anyway). We shouldn't do scaffolding here, I entirely agree, but to argue that we shouldn't do this because "scaffolding is complicated" is a slippery slope argument.

**Comment by anurse** [comment]
Personally I think DNU itself shouldn't be in the runtime but that's a discussion for a different thread :)

**Comment by davidfowl** [comment]
> If we have the ability to produce (pack, wrap, build, etc.) and consume (restore) packages in dnu then I don't see a problem with a simple command to initialize a project (which is how we expect people to create packages anyway). We shouldn't do scaffolding here, I entirely agree, but to argue that we shouldn't do this because "scaffolding is complicated" is a slippery slope argument.

This is better served as a global command. Maybe some of the others will be moved out as well.

> Personally I think DNU itself shouldn't be in the runtime but that's a discussion for a different thread :)

I agree. We planned to move it out but it's more trouble than it's worth at this very moment. When things are more stable it'll be more realistic. We even made a repository for dnu at some point.
