### ISSUE TITLE
Cannot run a DNX Web project from VS without dnx451 (beta6), or at all on beta5: gives strange build # in error. 

### ISSUE THREAD

**Issue by MattGal** [aspnet/dnx#2388]
I'm seeing two peculiar issues here.  These may be related to the automatic choices made when selecting runtime due to what Eric describes in issue #2387 

1) On VS 2015 RTM bits:

- Web Tools Extensions (WTE) includes all needed beta5 stuff, and all the packages I could find from it are non-timestamp. 
- If I create a new beta5-templated web project, simply change the frameworks entry from dnx451 to dnx452, I get this error from both browser AND command line (Dnx . web): 

Current runtime Target Framework: 'DNX,Version=v4.5.1 (dnx451)'
 Type: CLR
 Architecture: x86
 Version: 1.0.0-beta5-***12103***

The fact that a non-final version here is suspicious.

2) On VS 2015 RTM + WTE / DNX public beta 6 bits:

- This one's stranger, as it works for dnx . web but fails F5 from VS with: 
Current runtime Target Framework: 'DNX,Version=v4.5.1 (dnx451)'
  Type: CLR
  Architecture: x86
  Version: 1.0.0-beta6-12256

If I have any combination that lacks dnx451, something goes weird... except when doing so from a command line with dnx . web, where all combinations work.  From trolling through, there is only one instance of a .json file anywhere in the dnx repro that references 452 or 46 without also referencing 451.

**Comment by MattGal** [comment]
Any workarounds?

**Comment by anurse** [comment]
Re 1, `dnx452` is not supported on `beta5`. The version number is expected, every DNX build has a build number, regardless of the actual version number, and we keep the build number in when reporting that version so that it's clear what build is in use.

Re 2, This is due to IIS starting up before DNX has a chance to set the framework version. We have a VS feature coming to smooth this out, but for now there is a workaround using an environment variable. See https://github.com/aspnet/Home/releases/tag/v1.0.0-beta6 and https://github.com/aspnet/dnx/issues/2367#issuecomment-125767070 for more

**Comment by anurse** [comment]
I think these issues are resolved (and related issues are tracked). Please re-open if you are still seeing issues.

**Comment by MattGal** [comment]
Glad there's a workaround, but can you clarify why I see beta5/beta6 versions with timestamps attached when hitting either issue?  Seems as if a non-final package were being used when doing this despite trying to keep my machine clean with "final" beta5 + 6 bits.

**Comment by anurse** [comment]
Are you seeing **packages** with the timestamped versions or just the error message you showed above? The latter is not because it's "unreleased", the final version still has a timestamp and we leave it in those errors to ease bug reporting. If `dnvm list` says you're running `1.0.0-beta6` or `1.0.0-beta5`, then you should be on the final release for that preview, regardless of that version number

If you are seeing packages with timestamps, it could be caused by our versioning and dev/release feed model. The timestamped versions are considered _higher_ than the non-timestamped "release" version because the "tag" (the part after the `-`) is simply sorted lexicographically (aka "ASCIIbetical" :)). So if you have restored from the dev feed before and haven't cleaned your package cache (`%USERPROFILE%/.dnx/packages`), we'll see those and use them even if you're only restoring from the release feed now.

It's an unfortunate side-effect of our versioning strategy and SemVer. I agree we need a better strategy there (ping @DamianEdwards). At this point I think our best option

**Comment by Eilon** [comment]
No current plans to change the version strategy...
