### ISSUE TITLE
[Announcement] dnu sources

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#2437]
Use this thread to discuss the announcement [here](https://github.com/aspnet/Announcements/issues/46).

**Comment by Daniel15** [comment]
Ideally this should pull the exact version of the source code used to build the module, rather than just pulling the master branch. This could be done through tags (for projects that always tag their releases) or by embedding the commit hash when packaging. Pulling master means the source code you get is most likely **not** the source code used to build the package, which limits its usefulness.

**Comment by davidfowl** [comment]
It uses the exact commit not the master branch

**Comment by Daniel15** [comment]
Oh awesome, thanks! It might be worth clarifying that in the announcement? It wasn't mentioned anywhere.

**Comment by Ercenk** [comment]
Sample link for the project.json example is broken. Correct is:
https://github.com/aspnet/Options/blob/dev/src/Microsoft.Extensions.OptionsModel/project.json
