### ISSUE TITLE
DNX error when running under 8.1 and Server 2012 R2

### ISSUE THREAD

**Issue by TheBlueSky** [aspnet/dnx#2646]
Hello everyone,

I wrote the simplest ASP.Net 5 application that I could write, then published it using:

`dnu publish --runtime dnx-clr-win-x86.1.0.0-beta7 --out ..\01.output --no-source`

and another time using:

`dnu publish --runtime dnx-coreclr-win-x64.1.0.0-beta7 --out ..\01.output --no-source`

I used Windows 10 Pro when I wrote, ran, and published the application. Then I wanted to try the portability of DNX and my application, so I tried running it under Windows 8.1 Pro and Windows Server 2012 R2, once using DNX 4.5.1 runtime and once using DNXCore 5.0 runtime; however, in all the tries DNX was showing and error dialog box:

    dnx.exe - System Error
    ---------------------------
    The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.

Is this an issue, or is there a minimum system requirements that Windows 8.1 Pro and Windows Server 2012 R2 don't meet?

**Comment by muratg** [comment]
:watch:

**Comment by moozzyk** [comment]
I tried both runtimes and could not repro this. I published using the commands from @TheBlueSky on Windows 10 and then copied the published folders to Win 8.1. and ran web.cmd script. In both cases I was able to start the app and send a web request successfully.

**Comment by muratg** [comment]
What carries `api-ms-win-crt-runtime-l1-1-0.dll` to the machine?  I wonder if @moozzyk's VM's already had these.

**Comment by moozzyk** [comment]
On Win8.1/2K12R2 we should not depend on this forwarder at all. Only onecore versions depend on this forwarder but they should not run on Win8.x/2K12R2. In addition nothing from the clr runtime depends on forwarders so it is weird that the issue also occurs for clr runtime. Finally dnx.exe itself does not depend on this forwarder as well and we load other dlls (including onecore) dynamically. If they fail to load (e.g. due to missing dependencies) there is no popup but an error printed to the console. So, it seems like in this case somehow dnx depends on `api-ms-win-crt-runtime-l1-1-0.dll` only that when I checked beta7 bits it did not:

dnx depends in the coreclr x64 beta7 runtime: 
```
    api-ms-win-core-errorhandling-l1-1-0.dll
    api-ms-win-core-sysinfo-l1-1-0.dll
    api-ms-win-core-libraryloader-l1-1-0.dll
    msvcrt.dll
    api-ms-win-core-synch-l1-2-0.dll
    api-ms-win-core-rtlsupport-l1-1-0.dll
    api-ms-win-core-processthreads-l1-1-0.dll
    api-ms-win-core-profile-l1-1-0.dll
```

dnx dependents in the clr x86 beta7 runtime:
```
   KERNEL32.dll
   ADVAPI32.dll
```

@TheBlueSky - can you share your published app so that I can take a look what's going on? Also can you turn on tracing (set DNX_TRACE=1) and run your app (both clr and coreclr versions) from command line and provide the output if you get any?

**Comment by TheBlueSky** [comment]
@moozzyk, I have what you asked for ready on [OneDrive](https://onedrive.live.com/redir?resid=C50EEEC1AD648A17!116772&authkey=!ANBJG2mA8v-74tY&ithint=file%2c7z)... but, where do cool kids upload their 24MB stuff to these days? :)

The 7-zip file contains (1) `dnu publish` output in "01.output" folder, (2) a screen-shot, "dnx.png", is the error dialog when I ran "kestrel.clr.cmd" on Server 2012 R2, (3) dnx output after enabling the trace, `SET DNX_TRACE=1`, in "1.dnx.trace.log", and (4) dnx exception in "2.dnx.exception.log".

Note that (1) I haven't touched the output in anyway except to create 2 batch files to run the application against the 2 runtimes, and (2) I'm developing and running the application on virtual machines.

**Comment by moozzyk** [comment]
I believe the issue here is the kestrel and not the dnx. If you go to either of runtime directory you published and you just run `dnx.exe` it runs correctly (i.e. you don't see the popup) right? With @halter73 we found that libuv used by kestrel is not built correctly and depends on things it should not (including the forwarder you mentioned):

```
Dump of file .\libuv.dll

File Type: DLL

  Image has the following dependencies:

    ADVAPI32.dll
    IPHLPAPI.DLL
    PSAPI.DLL
    USERENV.dll
    WS2_32.dll
    KERNEL32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
```

This will be fixed as part of https://github.com/aspnet/KestrelHttpServer/issues/50. For now there is not a good workaround besides copying the missing files to the runtime folder.

**Comment by hoyanf** [comment]
[Another possible solution](https://support.microsoft.com/en-au/help/2999226/update-for-universal-c-runtime-in-windows)
Probable cause :-
> Microsoft Visual Studio 2015 creates a dependency on the Universal CRT when applications are built by using the Windows 10 Software Development Kit (SDK). You can install this update on earlier Windows operating systems to enable these applications to run correctly.
