### ISSUE TITLE
*.Sources packages should not have assemblies in them

### ISSUE THREAD

**Issue by muratg** [aspnet/dnx#2720]
These are Source only assemblies. The packages currently contain assemblies inside `lib` folder.

**Comment by Eilon** [comment]
Is that the full problem, or is the problem that despite there being a DLL in the package, it shouldn't get copied to the output directory of the consuming package?

I suppose fixing just this would likely solve the entire problem though.

But I'm mostly concerned about the .Sources.dll file appearing in the output of the consuming project.

**Comment by borgdylan** [comment]
If the assemblies will be removed consider changing some of those projects to normal ones. There are utilities like the CommandlineUtils that get used by people that are not necessarily on c#. In that case they cannot use the shared source code so they would need to reference the compiled library instead.

**Comment by anurse** [comment]
Well, the problem with that is that the dll would be completely empty. We auto-exclude "shared" files from compilation. If a binary package is needed, we'd produce a separate non-Sources build.

**Comment by borgdylan** [comment]
That would be the right thing to do. Do you make a non-sources build for anything that is non-internal and useful to the DNX ecosystem in general?

**Comment by anurse** [comment]
We do not at the moment because those packages aren't really designed for "official public consumption" (which is a major reason they are Sources packages). Others have and do use them and that's OK, but they are only officially supported as Sources packages.

We could discuss making official binary distributions but I'm not sure we are prepared to do that for 1.0.0. In the interim, you could totally just take the source and build it into your own binary package.
