### ISSUE TITLE
need DTH send us a new property saying which dependency in the dependency graph wins and it’s version is used elsewhere

### ISSUE THREAD

**Issue by abpiskunov** [aspnet/dnx#2744]
: In order to implement this spec: https://github.com/aspnet/specs/blob/master/tooling/different-package-versions.md we would need DTH send us a new property saying which dependency in the dependency graph wins and it’s version is used elsewhere. I checked DTH log and in the graph we receive I don’t have info I could use.

**Comment by troydai** [comment]
We will add a boolean property to the type representing the dependency to indicate if this dependency overrides other dependency.

**Comment by muratg** [comment]
Tentatively putting this in Beta8, though if it doesn't fit, we'll need to move.

**Comment by troydai** [comment]
@abpiskunov it can't be determined which dependency actually wins and override others because it is possible multiple dependencies meet the requirement. In addition the current lock file doesn't provide enough information for DTH to peak into the decision making process to gain the knowledge. The best we can do is to have boolean on dependencies to clear state if it is overridden, which means the actual version is not the requested version.

**Comment by troydai** [comment]
To: @DamianEdwards @abpiskunov @davidfowl 
CC: @BillHiebert @muratg 

Subject: __Change the solution__

Base on the idea that we want to have the information of what dependency overrides the other, I build this prototype to demonstrate what the response will look like in DTH. (https://github.com/aspnet/dnx/tree/trdai/dnx2744)

Since we can't deterministically tell what exactly caused the overridden, the prototype tries to list all the "winner" dependencies paths. When tested in 'MVC.sln', I found that the prototype increase the size of the response dramatically and the result is extremely noisy. For example this is an extreme case
``` JSON
    "System.Reflection.Primitives": {
      "Name": "System.Reflection.Primitives",
      "DisplayName": "System.Reflection.Primitives",
      "Version": "4.0.0",
      "Path": "C:\\Users\\trdai\\.dnx\\packages\\System.Reflection.Primitives\\4.0.0",
      "Type": "Package",
      "Resolved": true,
      "Dependencies": [
        {
          "Name": "System.Runtime",
          "Version": "4.0.21-beta-23405",
          "Override": true,
          "OverrideBy": [
            "Microsoft.AspNet.Mvc/6.0.0 => Microsoft.AspNet.Mvc.ViewFeatures/6.0.0 => Microsoft.AspNet.Diagnostics.Abstractions/1.0.0-rc1-15849 => System.Runtime/4.0.21-beta-23405 => END",
            "Microsoft.AspNet.Mvc/6.0.0 => Microsoft.AspNet.Mvc.Razor/6.0.0 => Microsoft.AspNet.Mvc.ViewFeatures/6.0.0 => Microsoft.AspNet.Diagnostics.Abstractions/1.0.0-rc1-15849 => System.Runtime/4.0.21-beta-23405 => END",
            "Microsoft.AspNet.Mvc/6.0.0 => Microsoft.AspNet.Mvc.Localization/6.0.0 => Microsoft.AspNet.Mvc.Razor/6.0.0 => Microsoft.AspNet.Mvc.ViewFeatures/6.0.0 => Microsoft.AspNet.Diagnostics.Abstractions/1.0.0-rc1-15849 => System.Runtime/4.0.21-beta-23405 => END",
            "Microsoft.AspNet.Mvc/6.0.0 => Microsoft.AspNet.Mvc.ViewFeatures/6.0.0 => Microsoft.AspNet.Antiforgery/1.0.0-rc1-15720 => Microsoft.AspNet.Http.Abstractions/1.0.0-rc1-15796 => System.Runtime/4.0.21-beta-23405 => END",
            "Microsoft.AspNet.Mvc/6.0.0 => Microsoft.AspNet.Mvc.Razor/6.0.0 => Microsoft.AspNet.Mvc.ViewFeatures/6.0.0 => Microsoft.AspNet.Antiforgery/1.0.0-rc1-15720 => Microsoft.AspNet.Http.Abstractions/1.0.0-rc1-15796 => System.Runtime/4.0.21-beta-23405 => END",
            "Microsoft.AspNet.Mvc/6.0.0 => Microsoft.AspNet.Mvc.Localization/6.0.0 => Microsoft.AspNet.Mvc.Razor/6.0.0 => Microsoft.AspNet.Mvc.ViewFeatures/6.0.0 => Microsoft.AspNet.Antiforgery/1.0.0-rc1-15720 => Microsoft.AspNet.Http.Abstractions/1.0.0-rc1-15796 => System.Runtime/4.0.21-beta-23405 => END",
            "Microsoft.AspNet.Mvc/6.0.0 => Microsoft.AspNet.Mvc.ApiExplorer/6.0.0 => Microsoft.AspNet.Mvc.Core/6.0.0 => Microsoft.AspNet.Hosting.Abstractions/1.0.0-rc1-15744 => Microsoft.AspNet.Http.Abstractions/1.0.0-rc1-15796 => System.Runtime/4.0.21-beta-23405 => END",
            // 600+ more overridden paths
           ]
        }
      ]
    }
```

What happened? A lot of the CoreCLR packages' references are not updated precisely. The overridden becomes a normal way to resolve the right packages. Given the dozens of small packages an CoreCLR project will introduce it easily causes a dramatically big results if we walk through every path in the dependency tree which involve dependency overridden.

After discuss with @DamianEdwards, we figured that changing the "Dependnecy" response is not the solution. Actually given that much information it may not be suitable for VS to handle the information. The idea came up is to expand the function of command `dnu list`.
1. Add a subcommand to request all the dependencies which requested version is different from the final version (the losing dependnecies);
2. Add a subcommand to dive into one specific dependency for its source. For a winning dependency, it is the full dependnecy path from root. For a losing dependency, it is the winning dependnecies who take over it. 

I'll close this issue and open new one on `dnu list`.

**Comment by troydai** [comment]
CC: @sayedihashimi

**Comment by abpiskunov** [comment]
Does it mean that we don't want to display a package with star icon now in VS? dnu list would work, but it would require user to switch to console and run this command which is too many steps ..., anyway if there no better way for now , lets go with dnu list ...

**Comment by troydai** [comment]
@sayedihashimi @DamianEdwards 
A simple Boolean value to indicate if a dependency is overridden is easy. If we still want to should some kind of indication in UI I can add the value to dependencies response.

**Comment by abpiskunov** [comment]
there not much value to show that version is overridden for a dependency, since user see it by the version itself.

**Comment by troydai** [comment]
Then I guess we close this case for now.

**Comment by abpiskunov** [comment]
You can send us info we need based on your own proposal: 1. create a first tree, 2. traverse the tree and see which package has other packages with same version but has Override = false, 3. send us final tree with info we need.  (we also could do it on tooling side, but it would be harder..)

Or if we don't want to do that , we need to close Tooling feature also and suggest users dnu list  (my question above)

**Comment by troydai** [comment]
Please check my previous commit for the reason why we can't do what you proposed here.

**Comment by sayedihashimi** [comment]
I'm going to add a backlog item to determine what we want here.
