### ISSUE TITLE
Embedded resources

### ISSUE THREAD

**Issue by angelsix** [aspnet/dnx#2804]
Do they exist any more in a DNX class library?

I have noticed there are no build actions anymore so no idea what happens when I place a file in the solution that used to be embedded such as an XML file.

Even if it now were embedded, how would I load that embedded resource as GetExecutingAssembly and GetManifestResourceStream are both missing too:

var assembly = Assembly.GetExecutingAssembly();
return assembly.GetManifestResourceStream(resourcePath);

**Comment by pranavkm** [comment]
To embed resources, use the `resource` node in project.json. See https://github.com/aspnet/dnx/blob/5bbb84bea40d8835da0c3eefd5a2343b50347084/misc/ResourcesTestProjects/testproject/project.json#L19-L26

`typeof(SomeTypeInYourAssembly).GetTypeInfo().Assembly` would be equivalent to `GetExecutingAssembly` and it has a `GetManifestResourceStream` method on it.

**Comment by angelsix** [comment]
Thanks thats done it :+1:

**Comment by DamianReeves** [comment]
It should be noted that at least in rc1 to get this to work properly with resource manager I also had to add a namedResource section:

```json
 "resource": [
        "*.resx",
        "Resources/*.resx"
    ],
    "namedResource": {
        "MyLib.Resources.ExceptionMessages": "Resources/ExceptionMessages.resx"
    }
```

**Comment by marchy** [comment]
Any ideas how to do this on RC2? It seems the various "resource" declarations are all marked as depracated.

**Comment by pranavkm** [comment]
@marchy See https://github.com/aspnet/Announcements/issues/175

**Comment by marchy** [comment]
Great thanks @pranavkm

**Comment by jimbuck** [comment]
For the time being I must stick with `dnx` instead of moving on to `dotnet`. I have english working fine with the resource manager but other cultures are not loading. I have `.resx` files for english, spanish, and chinese.

Files (in project root):
- UiStrings.resx
- UiStrings.es.resx
- UiStrings.zh-tw.resx

Here is a sample of my `project.json`:

``` json
"resource": [ "*.resx" ],
"namedResource": {
  "My.App.UiStrings": "UiStrings.resx"
}
```

Am I referencing them correctly? Do I need to generate `.resources` files for each language? If I create a build step that generates `.resources` files how would my configuration change?
