### ISSUE TITLE
dnu publish doesn't copy runtime specific packages to output

### ISSUE THREAD

**Issue by troydai** [aspnet/dnx#2930]

**Comment by muratg** [comment]
@BrennanConroy please sync-up with @victorhurdugaci and @troydai.  This issue is basically putting more runtime.* packages in DNX.  One particular example they found was to do with System.Net.Http.

This would be a workaround, and https://github.com/aspnet/dnx/issues/2850 would solve this issue in RC1.

**Comment by muratg** [comment]
@victorhurdugaci, @troydai Brennan made this change yesterday. Can we verify the issue is resolved (or at least worked-around? :smile:)

**Comment by muratg** [comment]
We have the workaround in Beta8.  Now we'll need to fix the publish properly.  Putting in RC1.
