### ISSUE TITLE
Support relative file paths for local feeds in nuget.config

### ISSUE THREAD

**Issue by danroth27** [aspnet/dnx#2965]
Looks like NuGet supports relative paths for local feeds: http://docs.nuget.org/consume/NuGet-Config-Settings. But this doesn't seem to work in DNX based projects (tested with beta7).

**Comment by leak** [comment]
Just stumbled across the same issue. It looks like the path is taken relative to the dnu / VS dnx working directory rather than the solution directory

**Comment by Grinderofl** [comment]
I'm battling the same bug right now with beta8 so it's very much still in play.

**Comment by csunali** [comment]
Would be great to see this feature implemented, since it also is supported by NuGet.

**Comment by csunali** [comment]
Well, it seems that this one actually works at the moment. It was my bad trying with a wrong path.

It takes paths relative to the `nuget.config` file.

**Comment by gotvino** [comment]
How did you get it to work? Path relative to nuget.config does not seem to work for me.

**Comment by csunali** [comment]
@gotvino, it does not work when VS tries to update your packages automatically. E.g.: you make a change to `projects.json` and save the file. You get plenty of exceptions.

However, if you run `dnu restore` from the Package Manager Console, things work.

I think that is because `dnu restore` command is run in the solution directory so it is able to find a relative path but when VS tries to restore the packages, it actually runs the process in VS directory. E.g.: `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE`
