### ISSUE TITLE
beta8 dnu restore required after publish

### ISSUE THREAD

**Issue by leak** [aspnet/dnx#3038]
Running beta8, building on TeamCity, publishing to a clean (no VS, etc.) deployment server.

After running the regular chain of 

````
dnu restore
dnu build
dnu publish (to server without VS being installed)
````
I would expect the published application be ready to go. If i try to invoke a custom dnx command for seeding the database I get:

``Error: . Please run "dnu restore" to generate a new lock file.``

**Edit

Running `dnu restore` on the published directory also breaks on certain dependencies:

MyApp (dnx web app)
MyLib (dnx class lib) <-- referencing 3rd party non-DNX library

There are multiple error messages during the restore process even though the libraries in question are present in the approot\packages and each one of them has both a project.json and a project.lock.json.

`Unable to locate Dependency Korzh.EasyQuery.DataGates.NET45 >= 1.0.0`

**Comment by NeelBhatt** [comment]
I guess It is more like a VS tooling issue. May be it is related to this:

https://github.com/aspnet/Tooling/issues/206

**Comment by leak** [comment]
VS is not involved in my build process. I build on a server running TeamCity (no VS) and i publish to another server (no VS either).

**Comment by moozzyk** [comment]
@leak have you tried publishing with `--no-source` and `--runtime` (if you don't expect the runtime to be on the target machine)? This should create a self contained app.

**Comment by leak** [comment]
@moozzyk Trying to publish with `--no-source` causes tons of dependency errors already during the publish process.

**Comment by leak** [comment]
I cannot reproduce the issue on RC1 anymore, seems to be resolved.

**Comment by barriestewart** [comment]
I know this is closed but I had the same error publishing an rc2 (using unstable sources) MVC project to a remote server. That was building in VSTS and pushing out to a Windows machine. Running `web.cmd` would throw this same error. It turns out the setting in VSTS to clean out the working copy folder on the build agent hadn't been ticked so we had some leftover files in there which caused the issue. Once we were making sure the working copy folder was clean, everything worked as expected.
