### ISSUE TITLE
Allow replacing the 'build' and 'pack' commands with scripts

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#3050]
Today we have `prebuild`, `postbuild`, etc. We should add `build` so that a user can change what happens on `dnu build`. Same for `pack`.

This allows more custom toolchains to integrate into the VS tooling, etc.

/cc @davidfowl

**Comment by marcind** [comment]
It would also be great if you could allow a hook to customize what goes into a nuget package (i.e. during the `pack` command enable hooking the moment after the build finishes but before the package contents gets specified).

Specific scenario: I want to customize my primary package (i.e. not the sources package) so that it includes the pdb file, which I want to customize using https://github.com/GitTools/GitLink.

It looks like the biggest impediment at the moment is the fact that the "postbuild" script runs after the package contents has been set (see. https://github.com/aspnet/dnx/blob/1bb5a1d24fcd7d21d2278528c243e2b9f181c43d/src/Microsoft.Dnx.Tooling/Building/BuildManager.cs#L231). I would expected it to run immediately after the build/compile step, so that I can mangle the build output once 

Some alternatives would be to have specific hooks for building the "source" package (and maybe even disabling that source package builds - I don't need both if I've customized the primary one).

**Comment by davidfowl** [comment]
Don't we have a prepack event?

**Comment by marcind** [comment]
You do, but the sequence is:
- prepack
- prebuild
- *Compilation*
- *Assembling list of things to go into package* <- not really customizable, at least not based on files in the output directory.
- postbuild
- *Generating package*
- postpack

I could hook postpack, do a bunch of unzipping, munging, and rezipping. I guess this is where having the build process implemented in code makes it less flexible (vs something like a well-designed set of msbuild targets). But then again, my scenarios is not something people typically do.

**Comment by anurse** [comment]
I think it makes sense to allow everything up to and including postbuild to (in theory) contribute to packaging. Could you use `packInclude` and `prebuild`? Or do you have to generate the files as part of the build?

**Comment by marcind** [comment]
I guess there's 2 scenarios here:

1. Customize the build process - the postbuild step is probably sufficient, esp. with the `project:BuildOutputDir` context var.
2. Customize package contents - this is hard, esp. if it's supposed to be based on dynamic content (i.e. the result of the build).

I'll probably stick to an external step that happens after `dnu pack`, since that way I can share the logic among a number different projects more easily.
