### ISSUE TITLE
Native artifacts not resolved when project

### ISSUE THREAD

**Issue by bricelam** [aspnet/dnx#3119]
When a reference is resolved via package, the `project.lock.json` file contains the following.

```JSON
{
  "targets": {
    "DNX,Version=v4.5.1/win7-x86": {
      "Microsoft.Data.Sqlite/1.0.0-t151102215934": {
        "type": "package",
        "native": {
          "runtimes/win-x86/native/sqlite3.dll": { }
        }
      }
    }
  }
}
```

However, when it is resolved via project with the following in it's `project.json`...

```JSON
{
  "packInclude": {
    "runtimes/": "runtimes/**"
  }
}
```

...the `project.lock.json` contains no `native` section.

```JSON
{
  "targets": {
    "DNX,Version=v4.5.1/win7-x86": {
      "Microsoft.Data.Sqlite/1.0.0": {
        "type": "project"
      }
    }
  }
}
```

**Comment by davidfowl** [comment]
It does't need one. We look at that data and at runtime figure out how to load it relative to the project. It's not spelled out but it's not an issue.

**Comment by moozzyk** [comment]
This is how we find the path for project references: https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Runtime/NativeLibPathUtils.cs#L32

**Comment by bricelam** [comment]
Interesting, I'll keep digging to figure out why it's not working...

**Comment by moozzyk** [comment]
Can it be because you have `win-x86` in the path and the runtime id is `win7-x86`?

**Comment by bricelam** [comment]
So fallbacks don't apply when it's a project? I'll try updating to win7.

**Comment by moozzyk** [comment]
There is a simple fallback model for project references but it is not as rich as for package references. Due to the schedule it was not feasible to change the code to use the same mechanism (and the code was still in flux). Here are the fallbacks recognized in project references: 
https://github.com/aspnet/dnx/blob/dev/test/Microsoft.Dnx.Runtime.Tests/NativeLibPathUitlsFacts.cs#L13-L18. The value goes to the `nativeSubfolder` in `Path.Combine(projectPath, "runtimes", nativeSubfolder, "native");` which is the path where dnx will look for the library.

**Comment by bricelam** [comment]
Ok, so I guess this bug is just that it doesn't fallback to "win", I'll switch to "win7" for now.

**Comment by moozzyk** [comment]
I opened the issue to track this #3132.

**Comment by bricelam** [comment]
Closing this issue. Everything is working with `win7`.

**Comment by moozzyk** [comment]
:clap:
