### ISSUE TITLE
Show error message when no global.json or project.json could be found

### ISSUE THREAD

**Issue by cH40z-Lord** [aspnet/dnx#3141]
When accidentally executing `dnu` restore in a classic .NET project which still uses `packages.config` no error message or hint is printed by `dnu` when trying to restore packages as you can see below.

![dnu restore](http://i.imgur.com/fumzvOr.png)

IMO, to enhance the entire user experience, at least an error including a hint should be printed.

**Comment by muratg** [comment]
dnu and nuget cmd line will be merged, and hence you'll be able to say `nuget restore` to restore for both DNX project.json, .csproj + project.json, and packages.config.

**Comment by lszomoru** [comment]
@muratg, could you please provide more details on the dnu and nuget merger? Will the merge happen in the dnx or nuget.client repos? Is there an issue that one could track to know when the merge completes? I am asking as I am currently blocked due to several bugs in dnu that should be fixed with the merger. Thanks!

**Comment by muratg** [comment]
Hey @lszomoru The merger is happening at the nuget org. You can watch nuget/home repo for related tickets. The goal is to have nuget ready enough by RC2 that `dotnet restore` command would be able to use nuget instead of dnu in RC2.  @yishaigalatzer could provide more info, and I recommend filing bugs in their repo if you have specific bugs you'd like to get tracked.

**Comment by lszomoru** [comment]
@muratg, thanks for the quick turnaround. I will make sure to keep an eye on the nuget/home repo. The good news is that the issues that I ran into with `dnu restore` are supported by `nuget restore` so the merger should unblock me. Really looking forward to the RC2 release!
