### ISSUE TITLE
[Announcement] Assemblies are now strong named

### ISSUE THREAD

**Issue by cesarbs** [aspnet/dnx#3156]
Discussion for https://github.com/aspnet/Announcements/issues/109

**Comment by MaximRouiller** [comment]
It was my impression that we were moving away from strong named assemblies. Or maybe I'm just mistaken. The fact that you have to validate an assembly while somebody already has access to your file system seemed a bit redundant. 

Are those assemblies for backward compatibility only?

**Comment by Eilon** [comment]
There are a number of reasons.

One reason we enabled strong naming is that we have cases where for a variety of reasons something that depends on the code here must be strong named, and so we must be strong named. (Strong naming is viral.)

Another reason (closely related to the first) is that in order to release critical security updates when running on .NET 4.x, we have to be able to install patches into the GAC, and the GAC requires strong naming.

**Comment by MaximRouiller** [comment]
There you go. I knew it must have been simple. 

Thanks!

**Comment by thecodejunkie** [comment]
"simple"

:)

**Comment by phillip-haydon** [comment]
Sigh. Fail Naming.

**Comment by davidfowl** [comment]
As a hater of strong naming I feel your pain. (intensely)

There's a few things that alleviate the pain when using our new toolchain and runtime, and changes to the process:

- You never really have to see binding redirects (we'll handle this either at runtime or by generating the right things on your behalf). If you do however use this with vanilla .NET in existing projects. All of the old problems exist. On MSBuild based projects that do not use our new tool chain, this is available https://msdn.microsoft.com/en-us/library/2fc472t2(v=vs.110).aspx.
- Unlike before, we're checking in the private key. There's no security feature (since strong naming isn't about security anyways). This means you can still swap packages with source on *any* OS and we'll do the right thing to make sure that works.
- The binding policy on CoreCLR means binding redirects are never a problem (all the more reason to move everything there as soon as possible :smile:).

It's disappointing that for .NET Framework, the problems all still exist but such is life...

**Comment by endeffects** [comment]
Hm, It looks like that the rc2 assemblies become incompatible to the rc1 assemblies because of the stronge naming. Which makes it hard to keep things working. Especially because the package restore seems not to respect the dependency versions: https://github.com/aspnet/dnx/issues/3152

**Comment by davidfowl** [comment]
@endeffects Package restore absolutely respects dependency versions. You're hitting something else altogether.

**Comment by Eilon** [comment]
@endeffects indeed an assembly would have to be recompiled across those versions. But with all the various renames and other changes, it is quite likely that a recompile would have to take place anyway in order to work.

**Comment by SamB** [comment]
@davidfowl:

> * Unlike before, we're checking in the private key.

Well, *that* certainly eliminates what could have been the main pain point going forwards!
