### ISSUE TITLE
Feature requests: Ability to import dependency and conditional dependency

### ISSUE THREAD

**Issue by ghost** [aspnet/dnx#3173]
Highly inspired by gyp.
### Scenario 1:

Ability to import a JSON.

`src/project.json`:

``` json
{
  "dependencies": {
    "foo": "v2.x",
  },
  "imports": ["platforms/commons.json", "../external/something.json"]
}
```

`src/platforms/commons.json`:

``` json
{
  "dependencies": {
    "bar": "v1.x",
  }
}
```

(same thing in `../external/something.json`)
### Scenario 2:

Ability to conditionally do stuff in `project.json`:

``` json
{
  "dependencies": {
    "foo": "v2.x",
  },
  "conditions": [
      [" custom_flag1 == '' || custom_flag1 == 'no' ", {
        "frameworks": {
          "dnxcore50": {}
        }
      }],
      [" custom_flag2 == 'yes' && custom_flag1 == 'no' ", {
        "frameworks": {
          "net451": {}
        }
      }]
    ]
}
```
### Scenario 3:

Putting it all together:

``` json
{
  "dependencies": {
    "foo": "v2.x",
  },
  "imports": ["platforms/commons.json", "../external/something.json"],
  "conditions": [
      [" OS == 'mac' ", {
          "imports": ["platforms/darwin.json"]
      }],
      [" OSClass == 'Unix' && OSSubClass != 'BSD' ", {
          "imports": ["platforms/unix-sans-bsd.json"],
          "dependencies": {
             "blah": "v1.2"
          }
      }]
    ]
}
```

Note the custom flags (the variables used in the conditions) can be set by runtime itself, passed by user to `dnu <service> --flag:custom_flag1=no --flag:custom_flag2=yes ..so on..` as well as defined as environment variables.

cc: @davidfowl

**Comment by davidfowl** [comment]
Scary. One of the things we set out to do was keep project.json fully declarative. Makes it easy to reasons about. It makes it really easy to write tools that understand the file format because there's no complex processing required.

What we've been successful at though is nailing specific use cases (like multi targeting framworks). So maybe explain what exactly you're trying to do might help design something less flexible but keeping inline with the current principles.

**Comment by jasonwilliams200OK** [comment]
I have a set of dependencies that needs to be incorporated when certain environment condition is met. I want to be able to put those dependencies in a separate file (scenario 1) as well as in the same file (scenario 2). DRY really: currently we would have multiple copies of project.json even for minor differences (e.g. https://github.com/dotnet/corefx/pull/4495/files#diff-6f96638be0e7a224da3e5a163abbaa64).

The given examples in my first post is a valid JSON so it won't break the tools. However, the tool would need to evaluate the expression in the conditions array. This might be the candidate of obscure usage at first glance, but with a simple expression evaluator incorporated, we can put this under "advanced" section in project.json. IMO, it is a powerful stuff in certain scenarios and gyp is a very good point of reference (node.js folks and chrome folks have examples all over the place :smile:).

**Comment by davidfowl** [comment]
> I have a set of dependencies that needs to be incorporated when certain environment condition is met.

What condition?

> However, the tool would need to evaluate the expression in the conditions array after the deserialization

Thats what I don't want though.

> This might be the candidate of obscure usage at first glance, but with a simple expression evaluator incorporated, we can put this under "advanced" section of project.json's usages. IMO, it is a powerful stuff in certain scenarios and gyp is a very good point of reference (node.js folks and Chrome folks have examples all over the place :smile:).

Personally I'd rather not tow the line between declarative and imperative, that's what msbuild does already.

Doing something like this will require lots of care and won't happen in the short term. I'm fine experimenting in the short term though. I just don't want this to turn into a full build dsl.

**Comment by jasonwilliams200OK** [comment]
> What condition?

Subjective; variables passed to dun process or environment variables in scenarios where multiple dependency choices are available for example.

> Personally I'd rather not tow the line between declarative and imperative, that's what msbuild does already.

I agree this would mess up the distinction and make the processing complicated, but on a bright side, we would have powerful semantics with a single point of failure. Once the import walker resolves and validate the chunks and stitch them together, the good old dumb (processed) JSON can also be produced.

If I understand it correctly, MSBuild step kicks in after the project.json is processed and settings are loaded. The functionality will be redundant in the sense of MSBuild but probably worth giving users a choice to declare their intent preemptively in JSON format.

>  I'm fine experimenting in the short term though.

If you want I can scribble down more granular set of rules pertaining to dependency walking, validations, variable declaration, expressions syntax etc. and propose an experimental implementation with some help from you guys. :)

**Comment by davidfowl** [comment]
> Subjective; variables passed to dun process or environment variables in scenarios where multiple dependency choices are available for example.

That's what I'm worried about :smile:

> I agree this would mess up the distinction and make the processing complicated, but on a bright side, we would have powerful semantics with a single point of failure. Once the import walker resolves and validate the chunks and stitch them together, the good old dumb (processed) JSON can also be produced.

TBH, imports aren't the worry, conditions are.

We do this already actually but kept it declarative. If you look at project.lock.json, there's a targets section there. It has `{tfm}/{rid}` pairs that get evaluated based context. When I said I want to avoid conditions, I mean arbitrary ones that require user input (it generally breaks too many things). So as an example, lets say we wanted to allow dependencies per runtime id (os and arch), we would have a section for that, generate the right data in the lock file and have the IDE and build tools evaluate that assuming they can provide the right context.

> If I understand it correctly, MSBuild step kicks in after the project.json is processed and settings are loaded. The functionality will be redundant in the sense of MSBuild but probably worth giving users a choice to declare their intent preemptively in JSON format.

When I mentioned MSBuild, I was thinking more about how it works today as a build engine that is used from the command line and the IDE. Today it's extremely hard to create an IDE context for msbuild projects because of the infinite flexibility allowed in those files. It's pretty much just code at that point (why not just write C#).

**Comment by jasonwilliams200OK** [comment]
Ok I realize that conditions will make things overly complicated.

> So as an example, lets say we wanted to allow dependencies per runtime id (os and arch), we would have a section for that, generate the right data in the lock file and have the IDE and build tools evaluate that assuming they can provide the right context.

It would be great to have tokens for OSes, OS versions and architectures. :smile: 

Given this scenario: https://github.com/dotnet/corefx/pull/4495/files#diff-6f96638be0e7a224da3e5a163abbaa64, having `src/unix/project.json` and `src/win/project.json` there is no way to exercise DRY. The correct `project.json` is selected based on the condition in csproj file.

Though in the existing lock file, it might be good to have common dependencies in addition to the selective for DRY'ing:

```json
{
  "locked": true,
  "version": 2,
  "dependencies": {  "common_dep": "2.x.x" },
  "targets": {
    "DNXCore,Version=v5.0,OSClass=Unix,Arch=amd64": {
      "dependencies": { "specific_dep": "3.x" },
    }
  }
}
```

**Comment by davidfowl** [comment]
> It would be great to have tokens for OSes, OS versions and architectures. :smile:

Here is what a runtime id looks like. https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json

It's an opaque thing that is defined by a package. OS and arch aren't really first class, but we use it that way. We've done a poor job at explaining how all of this works.

> Given this scenario: https://github.com/dotnet/corefx/pull/4495/files#diff-6f96638be0e7a224da3e5a163abbaa64, having src/unix/project.json and src/win/project.json there is no way to exercise DRY. The correct project.json is selected based on the condition in csproj file.

Yes I agree that should go away. When it originally came up I spoke to @ericstj and @stephentoub about it and that was the current short term solution. I think it makes sense to make it so that you can consume/produce rid specific and framework specific packages in `project.json`. It's yet to be implemented.

> Though in the existing lock file, it might be good to have common dependencies in addition to the selective for DRY'ing:

Heh, could be but it doesn't matter since it's machine generated. There's tons of crap in there already.

**Comment by davidfowl** [comment]
With msbuild, you can do this now 😄
