### ISSUE TITLE
Cant start dnx web

### ISSUE THREAD

**Issue by Ph47** [aspnet/dnx#3281]
From yesterday i cant start vNext web site nor by console nor by visual studio.

Exception is:
```
System.TypeLoadException: Could not load type 'Microsoft.AspNet.Hosting.Program' from assembly 'Microsoft.AspNet.Hosting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.AspNet.Server.Kestrel.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```
I have tried to use web listener and kestrel.

Config is:
```
{
  "webroot": "wwwroot",
  "version": "1.0.1",
  "exclude": [
    "wwwroot",
    "bower_components",
    "node_modules"
  ],
  "packExclude": [
    "node_modules",
    "bower_components",
    "**.kproj",
    "**.user",
    "**.vspscc"
  ],
  "dependencies": {
    "Microsoft.Extensions.Configuration": "1.0.0-rc2-*",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-*",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-*",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-*",
    "Microsoft.Extensions.PlatformAbstractions": "1.0.0-rc2-*",
    "Microsoft.AspNet.Hosting": "1.0.0-rc2-*",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc2-*",
    "Microsoft.AspNet.Diagnostics": "1.0.0-rc2-*",
    "Microsoft.AspNet.Mvc": "6.0.0-rc2-*",
    "Microsoft.AspNet.Owin": "1.0.0-rc2-*",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc2-*",
    "EntityFramework.Core": "7.0.0-rc2-*",
    "HttpMultipartParser": "1.1.4",
    "HangFire": "1.5.3",
    "Microsoft.Bcl": "1.1.9",
    "MySql.Data": "6.9.8",
    "Lucene.Net": "3.0.3",
    "ImageProcessor": "2.3.0",
    "Microsoft.Dnx.Runtime.Abstractions": "1.0.0-beta8-*"
  },
  "frameworks": {
    "dnx46": {
      "frameworkAssemblies": {
        "System.Drawing": "4.0.0.0",
        "System.Data": "4.0.0.0"
      }
    }
  },
  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel --server.urls http://localhost:5006",
    "ef": "EntityFramework.Commands"
  }
}
```

Dnvm is v1.0.0-rc1-15532
Runtime is 1.0.0-rc2-16343

**Comment by GuardRex** [comment]
Don't mix rc1-final, beta8, and rc2 all together like this. Bound to cause issues.

**Comment by GuardRex** [comment]
... also, you can drop the "webroot": "wwwroot" and update for the new hosting: https://github.com/aspnet/Hosting/issues/525#issuecomment-166487480

**Comment by Ph47** [comment]
GuardRex thanks for direction! I have nuget links for rc2. But where to find link to dnvm rc2? And VS do not suggest kestrel higher what 1.0.0-rc1-final. I tried WebListener rc2, same exception.

I ll try Main solution, thx for link.

**Comment by GuardRex** [comment]
Dnvm doesn't have a version like the packages do. When you run `dnvm update-self`, you will get the most recent version.

For Kestrel, try 1.0.1-

**Comment by GuardRex** [comment]
Actually it should be 1.0.0-rc2-16196

**Comment by GuardRex** [comment]
Make sure you have a package source for 
```
https://www.myget.org/F/aspnetvnext/api/v3/index.json
```

**Comment by davidfowl** [comment]
The problem is that you're using RC2 and not following along with the announcements repository. There are breaking changes in RC2 (and looking at your `project.json` RC1 as well) that you haven't accounted for.

https://github.com/aspnet/Announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-rc2

**Comment by Ph47** [comment]
davidfowl thx! i am watching this repo now.

**Comment by TotzkePaul** [comment]
Thank you @davidfowl. I've been trying to get an MVC website to run on a Linux VM and your comment on RC2 breaking changes helped me figure out the problem.

**Comment by proftom** [comment]
I had this issue after following the tutorial: https://docs.asp.net/en/latest/tutorials/your-first-mac-aspnet.html#developing-asp-net-applications-on-a-mac-with-visual-studio-code

Note that I installed everything using the installer (rather than the CLI or homebrew) - https://docs.asp.net/en/latest/getting-started/installing-on-mac.html#install-asp-net-5-with-visual-studio-code

After getting the error after trying to run dnx web, I then tried running

> dnvm update-self

and got:

`~/.dnx/dnvm/dnvm.sh doesn't exist. This command assumes you have installed dnvm in the usual location and are trying to update it. If you want to use update-self then dnvm.sh should be sourced from ~/.dnx/dnvm. dnvm is currently sourced from /usr/local/lib/dnx/bin/dnvm.sh`

At this point I decided that maybe the installers put dnvm not in the usual place and I'd try running the command line installations to see if they'd fix that (3 lines in total):
https://docs.asp.net/en/latest/getting-started/installing-on-mac.html#install-asp-net-5-from-the-command-line

I then was able to run 

> dnvm update-self

And it appears to be working. Not quite sure what I did, but figured I'd post it here as this post gave me the motivation to fix dnvm update-self.

Also that tutorial talks about some blank project with _"Hello World"_ in the startup.cs. Where was this. The blank project I created as per the yeoman tutorial has a totally different looking startup.cs? Where was this project? Further, vscode didn't have syntax highlighting/colourising for c# files (.cs) and the DNX commands didn't appear. To install these I had to run Extension: Install Extension from within the vscode command line (command shift p) then search for CS (took a while to install) and dnx. 

Hope this information helps someone in the future.
