### ISSUE TITLE
dnx dies silently on Linux with CoreCLR runtime

### ISSUE THREAD

**Issue by AlexanderElyseev** [aspnet/dnx#3284]
Hi!
After clean installation of dnx (Ubuntu Server 15.10) I have this behavior.
With mono runtime:

```
alexander@server:~$ dnx
Microsoft .NET Execution environment Mono-x64-1.0.0-rc1-16231
...
```

With CoreCLR runtime:

```
alexander@server:~$ dnx
alexander@server:~$
```

(the same with dnu)

Any suggestions?

**Comment by muratg** [comment]
Not sure what the issue may be.  Could you try `dnu restore -v` (for verbose output) to see if you have any error logs coming out?  

In any case, as we're retiring dnx/dnu/dnvm toolchain and will move to [dotnet CLI](https://github.com/dotnet/cli) in RC2, this won't be fixed in dnx.

I recommend giving dotnet CLI a try on that machine, and filing bugs in that repo if there are issues.

**Comment by cnblogs-dudu** [comment]
Try the following commands from [here](http://www.cnblogs.com/durow/p/5076829.html#3335223).
```
wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu52_52.1-8ubuntu0.2_amd64.deb
dpkg -i libicu52_52.1-8ubuntu0.2_amd64.deb
```
