### ISSUE TITLE
Inject LibraryDescription in LibraryManager at Runtime

### ISSUE THREAD

**Issue by xs2sachin** [aspnet/dnx#3370]
Hello,

We are developing a project, in which user can subscribe to apps at runtime, which is nothing but extended MVC project. we are able to locate the controllers and view at runtime, but unfortunately ICompilationService is not able to compile the view as it is using model from the extended assembly. 

Getting the following error:
An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.

After analysing it further, got to know that ICompilationService looking for assembly details in LibraryManager/LibraryExporter to compile the view. As assemblies being added at runtime, not able to find the LibraryDescrition at runtime

So, My question is it possible to add LibraryDescription or extended Library Manager, in RC1 at runtime in the LibraryManager collection?

**Comment by davidfowl** [comment]
Possible? Sure, it's an interface so you can implement your own. Of course, nuget was the one doing dependency resolution so if your implementation adds things at runtime, that's your job. Or maybe it won't matter since everything uses the same versions of stuff anyways...

It would be better to replace an mvc specific interface rather than something as big as library manager and library exporter.

**Comment by xs2sachin** [comment]
Thanks a lot for your timely response, I just want to leverage the core MVC as must possible. As Library Manager is being used in many interfaces, I was looking to option through which we can add new LibraryDescription values in the LibraryManager's collection.
