### ISSUE TITLE
Build web app works fine, even though there are build errors in dependent class lib

### ISSUE THREAD

**Issue by balachir** [aspnet/dnx#583]
1. New Empty web app : EmptyApp3
2. Add new class lib : ClassLibrary1
3. Add code in EmptyApp3\Startup.cs like this:
```C#
app.Run(async context =>
{
    await context.Response.WriteAsync(new Classlibrary1.Class1().GetHello());
});
```
4. Generate method in ClassLibrary1 
5. Make a typo in the code for ClassLibrary1
6. Build EmptyApp3

ACTUAL
Build succeds both in VS and in command-line (kpm build)

EXPECTED
Build to fail

**Comment by davidfowl** [comment]
Punting this. It works in VS only for now. There are challenges with making this work well.

**Comment by ChengTian** [comment]
Yeah, and the current behavior makes sense in some perspective:

When `ProjectA` depends on `ProjectB` and you want to compile `ProjectA`, Roslyn only extracts the minimum knowledge that `ProjectA` needs from `ProjectB`. We don't need to know implementation details in `ProjectB` in order to build assemblies from `ProjectA`, so as long as interfaces in `ProjectB` look good, we can build `ProjectA` successfully.

If you want to check all compiler errors in `ProjectB`, you need to compile `ProjectB`. Compiling `ProjectA` only checks interfaces in `ProjectB` for you.

**Comment by davidfowl** [comment]
CLI mitigates this
