### ISSUE TITLE
KPM pack --no-source generates a wrong web.config for IIS

### ISSUE THREAD

**Issue by ianhong** [aspnet/dnx#860]
Hi,
With the no-source option, KPM pack generates the following web.config. 

```
    <add key="kre-package-path" value="..\approot\packages" />
    <add key="kre-version" value="1.0.0-beta1" />
    <add key="kre-clr" value="CLR" />
    <add key="kre-app-base" /> // [ianhong]-> It has no value!!. If I set this value correctly, it works fine. 

```

Because of this, if I configure IIS to points to the wwwroot, the browser reports the following error:

Server Error in '/can' Application.

Unable to locate project.json 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.Exception: Unable to locate project.json

Source Error:

**Comment by djanosik** [comment]
I believe this bug still exists. I have an application called *WebSite* and I use the following command to bundle / publish it.
```
kpm bundle --out "C:\Bundles\WebSite" --configuration Release --no-source --runtime kre-clr-win-x86.1.0.0-beta3 --quiet
```
First time it works as expected and the `kre-app-base` setting has a correct value. But second time, the value is empty. It seems it is because the *C:\Bundles\WebSite\approot\packages\WebSite\1.0.0* folder already exists.

When I delete this folder, the package is rebuilt and the `kre-app-base` value is correct.

**Comment by ChengTian** [comment]
Cannot reproduce with latest version of `kpm`. Seems fixed.

**Comment by ChengTian** [comment]
BTW, `kpm bundle` doesn't read output folder, so existence of a certain folder in output shouldn't affect behavior of `kpm bundle`

**Comment by Krizzzn** [comment]
The `kre-app-base` is set as expected when using the `--overwrite` switch. Without `--overwrite` the key is empty when the target directory exists.
