### ISSUE TITLE
Reference an assembly from ASP.NET 5 projects

### ISSUE THREAD

**Issue by ChengTian** [aspnet/DNX#955]
Here is the spec I can think of

`kpm wrap <path_to_dll> --target-json <path_to_project.json>`

If `--target-json` is not given, we resolve the root dir using `<path_to_dll>` as a start point, and create `project.json` in `<root_dir>/wrap/<assembly_name>` for the assembly.

@davidfowl , please correct me or add more details. Thanks.

**Comment by ChengTian** [comment]
We might want to use a different approach to wrap an assembly. @davidfowl 's idea is:
`kpm packages add/make <assembly>`.

We won't have this in beta3.

**Comment by gulbanana** [comment]
could something like this be used by VS to support 'referencing' non-C# projects from asp.net 5 projects?

**Comment by ChengTian** [comment]
@gulbanana , after we have this command, it's possible that VS uses it as an underlying command to implement that.

Hi @PradeepKadubandi , does Tooling team have any plan for the feature mentioned by @gulbanana above?

**Comment by ChengTian** [comment]
Talked to @davidfowl , we the generated wrapper `project.json` should be in `<rootDir>/wrap/<assemblyName>`. `<rootDir>` should be resolved using `Directory.GetCurrentDirectory()` as a start point.

**Comment by ChengTian** [comment]
Dup of https://github.com/aspnet/DNX/issues/1316

**Comment by gulbanana** [comment]
Nice, that new issue will definitely meet a use case for my project

**Comment by davidfowl** [comment]
@gulbanana bare in mind that you cannot publish nuget packages that reference assemblies to nuget.org. This is mainly for apps.

**Comment by gulbanana** [comment]
No equivalent of 'copy local' for the assemblies, then? Presumably we can just use a manual build script and the old nuget.exe to create the package as a workaround.

**Comment by davidfowl** [comment]
Copy local assemblies for what? The nuget package? Like I said, for applications it's fine because there is an equivalent of copy local (a local file system publish) for deployment. 

For a class library, there isn't an equivalent. The sharing mechanism is NuGet and we don't generate packages with multiple assemblies. So MyProject -> Foo.dll, you'll end up with a package that depends on a another package called Foo. You'll just have to wrap Foo in a package (which this feature gives you for free since it wraps your assembly), and assuming that you own Foo as well, then you can push the closure of packages to whatever source you need to.

**Comment by gulbanana** [comment]
I mean that once the dlls are built, having referenced them via this mechanism, we'll just manually combine them into a single package rather than using kpm pack. (Though it is indeed for internal distribution).

**Comment by davidfowl** [comment]
If this is a library, just make each assembly a package.
